### ISSUE TITLE
Поддержка загрузки нескольких файлов на 1 хостинг, если хостинг это поддерживает.

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#107]
Пример #106 

для xml определить атрибуты:
multi_upload = true/false - поддерживает ли такое сервер
multi_max = int - кол-во файлов которые сервер примет один запросом. Где-то 2, где-то 5, где-то вагон и две тележки. 

По части скриптов, дать бы доступ к списку файлов в очереди(массив UploadFilesQueue какой-нибудь с FileQueueItem), с возможностью ставить им статусы(сообщение ядру) что файл забран в текущую передачу.

закинул в запрос FileQueueItem[0].FilName с 1 по пятый файл, как надо. проставил статусы FileQueueItem[0].State = PUTINREQUEST = 1, дефолтный какой-нибудь AWAITING = 0

и ушли один запросом толпа файлов на хост. Далее разбор ответа, выборка ссылок
FileQueueItem[0].State = UP_SUCCESS // уведомили что файл загружен
FileQueueItem[0].DirectUrl = 1312131 //дали на него ссылку

загрузчкик в конце вываливает перечень файлов и ссылки на них.

**Comment by zenden2k** [comment]
А смысл? это усложнит внутреннюю логику

**Comment by arhangelsoft** [comment]
Если хостинг поддерживает такое, почему бы не поддерживать и IU?

Я бы не сказал что это что-то усложнит, скорее переработает.

UploadFile просто будет таким:
`UploadFile(FilesQueue,settings)`
FilesQueue - очередь загрузки.
если 1 файл, берем FilesQueue[0].FileName
Если много, берем из очереди столько сколько надо, если доступно.

**Comment by zenden2k** [comment]
В любом случае, код, отвечающий за аплод будет основательно переписан для поддержки многопоточности, так что может быть и это попутно сделаю.

**Comment by arhangelsoft** [comment]
ну это радует... будет радовать ещё сильнее, если откажетесь от высказывания "Нет не подходит, на старых версиях работать не будет" :)

**Comment by zenden2k** [comment]
Кстати, я до сих пор Win 2000 поддерживаю :D
![lol](http://fs2.directupload.net/images/150401/bd6qiix8.png)
Причем один человек жаловался!!! что программа не работает на Windows 98 :lol:  через unicows.dll :lol:

**Comment by arhangelsoft** [comment]
![o_O](http://cs416331.vk.me/v416331607/4eb0/zO9Z4okOS9Y.jpg)

**Comment by zenden2k** [comment]
Этого не будет.
