### ISSUE TITLE
Custom scriptable dialogs

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#114]
Суть:
Через скрипты можно будет создавать визуальные окна, соответственно это дает куда больше возможностей.
1. Окна настройки и загрузки.
2. Окна авторизации(кастомные), параметров сервера.
3. Окна настройки аккаунта.
   
   И много-много других мест где их можно было бы приписать....

Многие сервисы, особенно картинок дают кучу крутых опций при загрузке картинок. 
Тоже для файловых хранилищ можно. 

Какой-нибудь класс:
CForm со ствойствами, событиями и методами и функциями.

Компоненты:
CLabel - метка
CButton - кнопка
CCheckBox - птыц
CEdit - поле ввода
CMemo - многострочное
CImage - пикча
CListBox - список строк
CComboBox - выпад. список
CMenu - меню
CPupupMenu - выпад. список

IDE для форм и скриптов могу я написать) т.е. полноценный редактор форм, редактор кода с подсветкой синтаксиса и мозгами при наборе кода.

Но нужно будет и формат скриптов поменять, опять же модульность в теме:
./HelloWorld.iusp - Image Uploader scriptable plugin
./info.txt - информация, что к чему
./icon.png - иконка расширения
./main.nut - пусковой скрипт
./forms/ - папка форм
./forms/hw.sform - форма, как JSON или XML, кароче чтобы IU могло по нему окно построить.
./forms/hw.nut - скрипт формы

как идейка?

**Comment by zenden2k** [comment]
Слишком сложно. Это надо будет для каждого контрола писать обертку, к тому же, я скоро собираюсь писать новый интерфейс на Qt, тогда придется делать сразу 2 реализации. Идея с GetServerParamListEx() мне нравится больше, тем более, что компонент, который используется в диалоговом окне, как я выяснил, поддерживает помимо edit box, еще combobox, checkbox.
Если так нужен кастомный диалог, можно использовать CWebBrowser и делать форму на HTML.

**Comment by zenden2k** [comment]
А на чем вы хотите IDE писать?

**Comment by arhangelsoft** [comment]
Можно писать на Lazarus, или сугубо под Win, на Delphi.

**Comment by arhangelsoft** [comment]
Так или иначе скрипт предоставляет сервис хостинга а не IU.

**Comment by zenden2k** [comment]
Нет, это не переписывание с нуля, а упрощенная версия для всяких линуксов и прочих макос.

**Comment by arhangelsoft** [comment]
Разве C++ не способен на это?

**Comment by zenden2k** [comment]
В смысле? Способен на что?

**Comment by arhangelsoft** [comment]
версия под Linux и Mac.

**Comment by zenden2k** [comment]
C++ - да, WTL - нет.
Qt это и есть кроссплатформенная C++ библиотека для GUI и не только.

**Comment by arhangelsoft** [comment]
Скорее платформа нежели библиотека.

**Comment by arhangelsoft** [comment]
Может это поможет) http://stackoverflow.com/questions/12717138/what-is-linux-s-native-gui-api

**Comment by zenden2k** [comment]
Я не собираюсь лезть в дебри, кроме Qt мне ничего не нужно.
Правда не всё так просто, есть еще зависимость от библиотеки Gdiplus, придется переписывать с использованием аналогов из Qt.

**Comment by zenden2k** [comment]
Случайно наткнулся на такое чудо:
![001.png](http://fs1.directupload.net/images/150506/b7vl2otr.png)

Наверно вы хотели что-то подобное сделать?
http://www.aimp.ru/blogs/?p=530

p.s. разработчик - маньяк

**Comment by arhangelsoft** [comment]
Да, что-то вроде этого можно было бы сделать.

штука называется LiveBindings, т.е. прямая связь между своством класса и визуальным элементом, обо всем остальном думает LiveBindings....
