### ISSUE TITLE
Как теперь вставить из буфера обмена?

### ISSUE THREAD

**Issue by ChizhDp** [zenden2k/image-uploader#118]
сабж

**Comment by zenden2k** [comment]
А раньше как?

**Comment by ChizhDp** [comment]
раньше на главном экране была кнопочка "Вставить из буфера"
сейчас ее нет

**Comment by zenden2k** [comment]
Еще актуально?

**Comment by arhangelsoft** [comment]
Так она никуда не убиралась. Если в буфере что-то есть, что поддерживает программа, то кнопка появляется.  Хотя кхм, с точки зрения юзабилити её надо бы показывать всегда, даже когда там не те данные, текст например, делать её не активной и при наведении выдавать текст, мол в буфере обмена не тот контент, то только тогда, когда буфер обмена не пуст.
