### ISSUE TITLE
Сжатие ссылок на картинки автоматом.

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#121]
в настройках указывается сервер по умолчанию, либо настраивается перед непосредственно загрузкой. 
После загрузки, прямые ссылки сжимаются через указанный сервис.

**Comment by zenden2k** [comment]
Я подумал, что в большинстве случаев это не нужно, поэтому спрятал эту возможность куда подальше

**Comment by arhangelsoft** [comment]
зачем же прятать? Пускай будет опционально))

**Comment by zenden2k** [comment]
Fixed in 1.3.2 branch

**Comment by vladios13** [comment]
Опционально это удобно!
