### ISSUE TITLE
После отмены выделения области, ИУ не реагирует на команды.

### ISSUE THREAD

**Issue by Mercury127** [zenden2k/image-uploader#124]
Хотим выделить область для снимка. Передумали, отменили (Esc). После отмены выделения области снимка, программа перестает реагировать на все хоткеи и команды в трее, кроме Выйти.

**Comment by zenden2k** [comment]
Это с отключенным редактором?

**Comment by Mercury127** [comment]
Нет, редактор тут ни причем. Извините, что сразу не выяснил. Это бывает, если «Использовать старый способ выбора области». Если использовать новый, то этого не наблюдается, зато наблюдаются жуткие тормоза по снятию затемнения экрана, после отмены по Esc.

**Comment by Mercury127** [comment]
И вдобавок, с новым способом, после нажатия Esc, сами собой переключаются окна, как если бы им послали Альт+Таб...

**Comment by zenden2k** [comment]
fixed
