### ISSUE TITLE
CIUUploadParams не знает ничего про логин и пароль

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#130]
Собственно ошибка или в доках или в коде. 
function UploadFile(pathToFile, options) {
	local lg = options.getParam("Login");
	local pwd = options.getParam("Password");

lg и pwd пустые, согласно докам должны быть полные.

Есть некий глобальный ServerParams в котором все это добро и лежит, в доках про него пусто.

**Comment by zenden2k** [comment]
http://rawgit.com/zenden2k/image-uploader/master/Docs/api_smallclasses.html#CServerParams
