### ISSUE TITLE
При создании скрина просто нет перекрестия которым выделяется область. 

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#135]
Тупо выделяю что там само выделится, а потом перетаскиваю область видимости куда мне надо. 

Это не есть хорошо.

**Comment by zenden2k** [comment]
Совсем нету? На самом деле этот курсор инвертирует цвет, то есть черный становится белый, белый черным, а серый.... серым

**Comment by arhangelsoft** [comment]
Ну я его точно не вижу и не нахожу на экране, мб. hand какой-нибудь был бы круче)

**Comment by zenden2k** [comment]
надо гдето найти нормальное перекрестие в хорошем разрешение

**Comment by arhangelsoft** [comment]
да системный icon-hand возьмите) курсор что над ссылками всплывает.

**Comment by zenden2k** [comment]
Наверно надо нарисовать курсор в виде белого креста с черной обводкой. Тогда будет виден на любом фоне.
Еще у меня есть идея сделать выделение как в Яндекс Диске - у них не делается предварительно статический скрин рабочего стола, поэтому например анимация, видео продолжает играть пока выделяешь прямоугольник. Наверно они делают окно поверх всех с полностью прозрачным альфа каналом

**Comment by zenden2k** [comment]
![test2](https://user-images.githubusercontent.com/2940480/49511473-546fcd80-f89c-11e8-88f3-9bbcf847e7b5.gif)

**Comment by zenden2k** [comment]
Поменял курсор
