### ISSUE TITLE
BuildBot

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#138]
Собственно возможно ли сделать авто-публикацию последних бинарников из исходников, без установщика?

**Comment by zenden2k** [comment]
Ну на сайте есть архив http://zenden.ws/ru/imageuploader_downloads
Правда оно не совсем авто, грубо говоря я делаю билд, потом запускаю Dist\create_all.bat,
потом upload_to_bintray.bat, потом нажимаю publish на bintray (потому что почему-то publish через REST API не работает), и меняю ссылки на сайте.

**Comment by arhangelsoft** [comment]
В MSVS есть post-build event, можно туда прикрутить отправку сабжа.. получится нормальный автомат. 
Запустит create_all, тот запустит и дождется upload_to_bintray.bat.

**Comment by arhangelsoft** [comment]
может сейчас есл разобраться, то REST заработает))

**Comment by zenden2k** [comment]
Не каждый билд, который я делаю, надо заливать на сервер.
Я его сначала  быстренько проверяю, потому что могут всплыть ошибки, которые в Debug версии не проявляются.

**Comment by arhangelsoft** [comment]
ну запилить конфиг git-build) какой-нибудь, дляэтих целей.

**Comment by zenden2k** [comment]
Хочу еще покрыть тест юнит-тестами, хотя бы основные классы.
И чтобы они автоматически выполнялись при каждом билде.

**Comment by arhangelsoft** [comment]
то сначала надо процесс до автомата до вести, и только потом уже можно внедрять юнит-тестирование.

**Comment by arhangelsoft** [comment]
только хотел QT вариант посмотреть)

**Comment by zenden2k** [comment]
Qt вариант пока не компилируется

**Comment by zenden2k** [comment]
Ура, я победил bintray 
https://github.com/zenden2k/image-uploader/blob/1.3.2/Dist/upload_to_bintray.bat

**Comment by arhangelsoft** [comment]
ура)) пойду обновлюсь... :+1:

**Comment by arhangelsoft** [comment]
Что делает режим разработчика? Что делает "выполнять squirrell-скрипт для каждого файла"?

**Comment by zenden2k** [comment]
>выполнять squirrell-скрипт для каждого файла
Вызывает squirrell-скрипт для каждого файла, до загрузки и после загрузки

Пример использования можно найти в файле Data\Scripts\UploadFilters\optipng.nut, 
который оптимизирует картинку с помощью optipng  
Еще пример
http://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=1151&limit=1&m=1#1

**Comment by arhangelsoft** [comment]
___
не кэширует скомпилированные скрипты
______
феерично плюсую.

**Comment by zenden2k** [comment]
Прикрутил нормальный html парсер

```
local txt = "<h1><a id=\"logo\">some link</a></h1>";
local doc = Document(txt);
print(doc.find("h1 a").text()+"\r\n");
print(doc.find("h1 a").length()+"\r\n");
print(doc.find("#logo").attr("class")+"\r\n");
    
nm.doGet("http://zenden.ws");
txt = nm.responseBody();
doc = Document(txt);
doc.find("a").each( function(index,elem) {
    print(elem.text()+"-\r\n"); 
});
```

**Comment by arhangelsoft** [comment]
вопрос исчерпал себя
