### ISSUE TITLE
Sqrat multithreading issue

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#139]
> Multiple VMs are supported. Multi-threading is not currently supported.
> The possibility of multi-threading has existed since commit [1f1061].
> In that commit, many bugs with having multiple VMs were fixed.
> However, all data that is shared between VMs is never locked.
> Sqrat has never locked this data, and it is necessary to be for multi-threading.
> You fixed a common race condition, but need to prevent a lot more.
> Basically, any time Sqrat is getting or setting shared data, it needs to be atomic.
> You can fix with locks and unlocks or another mechanism.
> If you make it in a way that is generic and conditional, I will accept your patch.
> However, know that this migrating to 0.9 likely just made multithreading crash more.
> Race conditions have always existed in Sqrat.
> About removing static variables, this is not possible without overhauling the API.

**Comment by zenden2k** [comment]
Пока вроде не падает, но кто знает, какими проблемами это обернется в будущем

**Comment by arhangelsoft** [comment]
Предположу что если будет 2 элементов очереди с разными параметрами (сейчас это не реально), ну там высота и ширина миниатюры, скорее всего где-то получение этих данных может пересечься.

Таки да, сабж о двух баранах на одном мосту.

**Comment by arhangelsoft** [comment]
Если уме можете это попробовать, определите 1 глобальную переменную, и попробуйте в неё писать из 3-5 вирт. машинок.

**Comment by arhangelsoft** [comment]
Может можно завернуть в это? http://scrat.sourceforge.net/threading.html

**Comment by arhangelsoft** [comment]
Подозреваю что то, о чем говорит автор в первом посте - всего лишь параллельная работа нескольких скриптов в одном контексте.

**Comment by zenden2k** [comment]
Нет, речь идет о работе разных виртуальных машин Squirrel в разных потоках (как сейчас сделано).
Общие данные скриптов я блокирую мьютексами.
Но сам Sqrat, как видите, официально не поддерживает многопоточность.

**Comment by arhangelsoft** [comment]
Надо бы поток сознания сливать в один пост...

**Comment by zenden2k** [comment]
>Может можно завернуть в это? http://scrat.sourceforge.net/threading.html
Нет, многопоточность ВНУТРИ скриптов не нужна

**Comment by arhangelsoft** [comment]
Есть офигенное предложение - заменить Squirrel на  тот же Lua, ввиду необходимых достатков а может и чуть больше.

**Comment by zenden2k** [comment]
> заменить Squirrel на тот же Lua
Нет. Когда я выбирал между Squirrel и Lua, я выбрал первый, потому что у него си-подобный синтаксис.

К тому же это недостатки не Squirrel, а обертки Sqrat.

**Comment by arhangelsoft** [comment]
мм дописать обертку тогда))

**Comment by zenden2k** [comment]
У lua паскалеподобный синтаксис

**Comment by arhangelsoft** [comment]
в упор не вижу ничего паскалевского, разве что end у функций. Остальное от C пришло.

**Comment by zenden2k** [comment]
дедлоки везде
печаль беда ((((
