### ISSUE TITLE
Список загрузокк не пуст, но в него не вернуться

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#141]
Собственно наплодить скриншоты, не загружать их. Жму кнопку "назад" в окне списка скринов, и вылетаю в главное окно. 
Все. 

Назад мне не вернуться, если я хочу загрузить уже добавленное.
По сути ПО никак не говорит мне что в списке что-то есть. 

Предлагаю в гл. окно добавить StatusBar с инфой:
Файлов в очереди загрузки: 0 <- отображать как ссылку, с подсказкой "Нажмите для открытия очереди".

**Comment by zenden2k** [comment]
А кнопка Вперед не работает?

**Comment by arhangelsoft** [comment]
_____
А кнопка Вперед не работает?
_____
вдруг я ещё скринов решил наделать?

**Comment by arhangelsoft** [comment]
вопрос исчерпал себя
