### ISSUE TITLE
drp.io

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#150]
http://drp.io/

**Comment by zenden2k** [comment]
Мне некогда заниматься добавлением новых хостингов, очень много фич, которые надо сделать,
можно попробовать сгенерить xml-код с помощью проги https://bintray.com/artifact/download/zenden/zenden-image-uploader/IU_Helper_0.1.1.7z
я обновил версию встроенного браузера

**Comment by arhangelsoft** [comment]
То я сам добавлю) закинул сюда,  пусть висит.

**Comment by arhangelsoft** [comment]
Попробую утилиту.
Вы все же на плюсах продолжаете или уже на котэ перешли?

**Comment by zenden2k** [comment]
qt это тоже C++. Эта утилита написана мной давно на кутэ (правда, не дописана)

Я решил, что почти всё ядро будет на чистом C++ (кроме работы с изображениями в линуксе), и 3 интерфейса - GUI на WTL и Qt, и консольная версия.

Пока переделываю архитектуру, чтобы Qt версия хотя бы могла скомпилироваться.

**Comment by zenden2k** [comment]
У меня есть очень кривой класс CSettings, на котором я застопорился.
Он у  меня единый для всех подпроектов ( GUI, консольная версия, расширение для проводника, и теперь еще Qt версия). 

Они используется у меня так:
```
Settingsю.LoadSettings(); // читаем из файла
 Settings.ConnectionSettings.ProxyPassword = Password;
 Settings.ConnectionSettings.ProxyType = PROXY_HTTP;

Settings.SaveSettings(); // сохранение в файл при выходе
```

Проблема в том, что у разных подпроектов разные настройки, но они пересекаются.
Вот думаю как это переписать под 4 подпроекта сразу
Через наследование как-то или я не знаю

**Comment by arhangelsoft** [comment]
Возможно ли использование интерфейсов? Lazarus к примеру умеет это кроссплатформенно делать. Что для Windows, что для Linux.

1. Они тупо удобны и можно сразу от пачки интерфесов наследовать гибрид.
2. За высвобождение памяти отвечает сам механизм интерфейсов. Программист забывает и может не думать об этом, своеобразный Grbage Collector. 

Далее, зачем куча ifdef для разных осей? Проблема же только в I/O-функциях. 
Напишите абстрактный CustomREaderи CustomWritter, от которых реализуете WinReader,LinReader,MacReadier, далее с Writer'ом тоже самое. 
Далее SettingsStorage котрый быет ссылаться на CustomReader а при инициализации класса, с пом. ifdef создвать нужные классы под разные ОС. Далее просто переходите на высокий уровень и вас более не парит как там на win,nix, mac будет записано и куда, прозрачно будет использован на 138% правильный класс.

**Comment by zenden2k** [comment]
В С++ можно использовать не только интерфейсы, но и множественное наследование. 
Но что-то не могу понять, как красиво реализовать.

В Qt вообще другой подход:
```cpp
Settings.getValue("ConnectionSettings/ProxyPassword");
Settings.setValue("ConnectionSettings/ProxyPassword", pass);
```

Возвращает всегда QVariant, и везде нужно преобразовывать типы. Но мне такой подход со строками  не нравятся.

**Comment by arhangelsoft** [comment]
Ну это излечимо в принципе, мб подойдет: http://habrahabr.ru/post/149085/ ?

**Comment by zenden2k** [comment]
Ха, я такой способ с enum уже пробовал, тоже с QMetaEnum, причем не читая этут статьтю.
Но мне не нравится, что везде надо делать преобразование типов, к тому же у меня нет ничего похожего на QVariant  да и не хочу я этого делать.

**Comment by arhangelsoft** [comment]
Ну наплодите readInt, ReadString, ReadBool :)

**Comment by arhangelsoft** [comment]
>>Похоже придется так и продолжать юзать кучу ifdef-ов :(

оч. плохая идея.

**Comment by zenden2k** [comment]
C++ не позволяет перегруженные функции с другим возвращаемым типом. Можно написать только так:

```cpp
int value;
string anotherValue;
Settings.getValue("Quality", value);
Settings.getValue("Name", anotherValue);
```

**Comment by arhangelsoft** [comment]
тогда свой класс со своим зоопарком геттеров и сеттеров. SetInt,GetInt и так далее....

**Comment by zenden2k** [comment]
Чувствую, придется все переписать с нуля,...

**Comment by arhangelsoft** [comment]
Indeed.

**Comment by zenden2k** [comment]
Нет, я всё таки хочу, чтобы типы сохранялись, и не надо было заботиться о праильном преобразовании типов.
Думаю сделать классы типо BaseSettings, ConsoleSettings, BaseGuiSettings, QtAppSettings, WtlAppSettings

**Comment by zenden2k** [comment]
Есть еще проблема с таким подходом, при выходе из программы одна копия программы перезаписывает настройки, измененные в другой копии.  В Qt такой проблемы нет.

**Comment by arhangelsoft** [comment]
>Нет, я всё таки хочу, чтобы типы сохранялись, и не надо было заботиться о праильном преобразовании типов.

Значит об этом надо думать ещё на низком старте. Либо зоопарк методос длягет/сет, либо javascript-стиль с магией обощенных типов данных, неким подобием typeof в С++
что-то типа этого:
void getValue(what, out v) {
 QVariant ret = null; 
::getValue(what,ret);
 if(typeif v == "string")
  v = ret.toString();
}

**Comment by arhangelsoft** [comment]
>Есть еще проблема с таким подходом, при выходе из программы одна копия программы перезаписывает настройки, измененные в другой копии. В Qt такой проблемы нет.

скорее всего файл с конфигом имеет имя exe. Потому они не пересекаются.

**Comment by arhangelsoft** [comment]
А так ли нужен вам macOS? 

Почему не написать все это на С# и пускать под Mono на Linux?

**Comment by zenden2k** [comment]
> скорее всего файл с конфигом имеет имя exe. Потому они не пересекаются.
Я имел ввиду запущенные копии одного и того же exe

**Comment by arhangelsoft** [comment]
о,а вот это уже интересно. Может просто "умно" записывает?

**Comment by zenden2k** [comment]
А может он записывает только значения при вызове setValue() и наверно как-то буфферизирует запись. На винде вообще по умолчанию сразу же пишет в реестр, но можно и в ini файлы или xml.

**Comment by zenden2k** [comment]
>Почему не написать все это на С# и пускать под Mono на Linux?

Да, почему бы не переписать всё с нуля?

**Comment by arhangelsoft** [comment]
>А может он записывает только значения при вызове setValue() и наверно как-то буфферизирует запись. На винде вообще по умолчанию сразу же пишет в реестр, но можно и в ini файлы или xml.

Я имел ввиду другое, там мб куча проверок. Например что записываемое значение чем-то отличается от уже записанного, и его надо перезаписать, если да, то записываем. И так далее.

>Да, почему бы не переписать всё с нуля?

На пороге Qt и та же фигня. Вот в чем вопрос.

**Comment by zenden2k** [comment]
Mono это не вариант. Под линуксом это выглядит не нативно и страшно.
Есть GTK#, но он в свою очередь под виндой выглядит ужасно.
Остается только Qt, он везде более-менее.

**Comment by arhangelsoft** [comment]
под линь вы же все равно консоль думали делать)

**Comment by zenden2k** [comment]
Почему консоль? Консоль уже есть?

**Comment by zenden2k** [comment]
Кстати, с консольной версией был, прикол, я никак не мог понять, почему на винде аплод идет гораздо медленнее чем в GUI и в линуксе.
Оказалось, что виндовая консоль намного медленнее выводит текст, чем в линуксе)))) 
пришлось ограничить частоту вывода прогресса.

**Comment by arhangelsoft** [comment]
либо посмотреть реализацию прогресса в UPX исходниках.

**Comment by zenden2k** [comment]
Просто библиотека libcurl вызывает callback слишком часто. Пришлось ограничить.
Я вот сейчас думаю, как сделать в консольной версии многопоточный аплод и вывод прогресса при этом. Наверно придется библиотеку ncurses использовать.

**Comment by zenden2k** [comment]
>Состаримся и мы и наши дети :D

Ну, тогда подожду, пока допилят QtSharp.

**Comment by arhangelsoft** [comment]
>Я вот сейчас думаю, как сделать в консольной версии многопоточный аплод и вывод прогресса при этом, и нужно ли это. Наверно придется библиотеку ncurses использовать.

многозадачность - однозначно плюс. На счет частыъх колбэков, модет поставить какой-то setTimer который будет сразу заворачивать колбэк curl'а,а когда сработает таймер он его разрешит на долю секунд, типа семафора что-то. Тогда консоль не так часто тупить будет..

А насчет прогрессбара от UPX все же посмотрите, красиво смотрится.

**Comment by arhangelsoft** [comment]
http://drp.io/ поддерживается. Закрывайте.

**Comment by zenden2k** [comment]
Где pull-request?

**Comment by arhangelsoft** [comment]
мне git не даёт :(

**Comment by arhangelsoft** [comment]
#166

**Comment by zenden2k** [comment]
Они официально поддерживают прямые ссылки?

**Comment by arhangelsoft** [comment]
в ответе отдают прямую ссылку.

**Comment by zenden2k** [comment]
Там ведь кнопка скачивания. Может, это временная ссылка? 
Ладно, посмотрим.
