### ISSUE TITLE
Из интернета "Вести наблюдение за буфером обмена"

### ISSUE THREAD

**Issue by maxvlas** [zenden2k/image-uploader#153]
**Из интернета - Вести наблюдение за буфером обмена**
Функция полезная,хорошая,но не стабильно работает.
Всегда каждый раз при копировании нескольких ссылок приходится каждый раз смотреть и проверять .скопировалась она или нет.
При заливке из буфера нескольких изображений (когда галка стоит)
http://fs1.directupload.net/images/150311/ag4dql4x.png
,допустим 5 изображений,то в окне бывает не все отображаются,могут все 5 ссылок появиться,а могут 3 или 4 всего 
Сейчас к примеру копировал по очереди 4 URL ссылки изображений.в окне смотрим,всего лишь 2
http://fs2.directupload.net/images/150311/88t4y8ic.png

**Вот  к примеру в яндексе взял любые фото природы:** 
http://www.activeclub.com.ua/modules/gallery/d/9196-1/105.jpg 
http://picsdesktop.com/Nature-autumn/1920x1440/www.PicsDesktop.com_265.jpg 
http://picsdesktop.net/summer/1920x1440/PicsDesktop.net_303.jpg 
http://funkyimg.com/i/bHC9.jpg 
http://www.compwalls.com/wallpapers/animated_home_in_nature-1920x1080.jpg 
________________________
Не знаю может от имен файлов влияет как то,если к примеру смотреть в окно программы и несколько раз продолжать копировать URL не скопированный фотки.то она вставляется когда со второго или третьего раза 

Неприятность и трата времени в том,что к примеру если не открывать и смотреть что скопировалось в окне,к примеру 7 ссылок скопировал по очереди в буфер.потом смотришь в конце а там не хватает одной или двух и приходится или заново проделывать или вычислять что именно не скопировалось. 

Не знаю может эта проблема в портативной только такая,потому как пользуюсь портативкой

**Comment by arhangelsoft** [comment]
Попробуйте использовать такую регулярку PRCE для загребния урлов:
`(\b(https?|ftps?|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])`
флаги: `igu`

работает с file://, http:// https:// ftp:// ftps://

**Comment by zenden2k** [comment]
Тут проблема не в регулярке, а в работе с буфером обмена

**Comment by zenden2k** [comment]
Проблема в том, что я понятия не имею, как это воспроизвести
![iu_buffer.gif](https://lh3.googleusercontent.com/-oebBmmpr4bc/VUppsssQQjI/AAAAAAAAFPQ/I4vnWyuZET4/s0/iu_buffer.gif)

**Comment by arhangelsoft** [comment]
стоит некое другое ПО, которое херит буфер :)

Напишите глобальный хук в dll, на WH_GETMESSAGE сабж https://stackoverflow.com/questions/18311274/monitoring-clipboard

**Comment by zenden2k** [comment]
Еще лишних dll мне не хватало. Используются обычные функции виндовые `SetClipboardViewer` и `WM_DRAWCLIPBOARD`

**Comment by arhangelsoft** [comment]
но буфер то кто-то же херит)

**Comment by zenden2k** [comment]
В прошлый раз программе мешал скайп, что на этот раз?

**Comment by zenden2k** [comment]
Прочитал в MSDN:
>The clipboard viewer chain can be broken by an application that fails to handle the clipboard chain messages properly. New applications should use more robust techniques such as the clipboard sequence number or the registration of a clipboard format listener.

Есть альтернативные методы, попробую использовать их

**Comment by zenden2k** [comment]
Проблема в том, что функция [AddClipboardFormatListener ](https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms649033(v=vs.85).aspx) поддерживается начиная с Vista, а у автора Windows XP

**Comment by arhangelsoft** [comment]
я думаю не понадобится. 
Посмотрел сорец. вы захватываете только CF_TEXT, а есть ещё CF_OEMTEXT, CF_UNICODETEXT, CF_STRINGCLASS, CF_HTML, CF_CSV

**Comment by arhangelsoft** [comment]
Туда же, вы не блокируете буфер перед сканированием, что важно. 
Юзайте OpenClipboard и CloseClipboard перед  после обращения, тогда прочий софт пойдет в топку.

**Comment by zenden2k** [comment]
Зачем мне какие то другие форматы клипборда? CF_text устанавливается всегда.
И буфер я блокирую.
```cpp
bool IU_GetClipboardText(CString& text)
{
    if (OpenClipboard(NULL))
    {
        HGLOBAL hglb = GetClipboardData(CF_UNICODETEXT);
        LPCWSTR lpstr = (LPCWSTR)GlobalLock(hglb);
        text = lpstr;
        GlobalUnlock(hglb);
        CloseClipboard();
        return true;
    }
    return false;
}

```

**Comment by arhangelsoft** [comment]
Может текст не всегда UNICODE и не всегда текст. Браузеры капризны.

**Comment by zenden2k** [comment]
С чего бы это ссылке быть не plain text?
CF_UNICODETEXT есть всегда, когда есть CF_TEXT!

**Comment by zenden2k** [comment]
oh shit, у меня github на windows xp не открывается))))

**Comment by arhangelsoft** [comment]
Все же здесь говорят что лучше самому разбираться что там UTF а что нет: https://stackoverflow.com/questions/15362859/getclipboarddata-cf-unicodetext

**Comment by zenden2k** [comment]
>GitHub will drop IE support for Windows XP users on January 5, in the name of security
блин хорошая же система

**Comment by arhangelsoft** [comment]
Система-то да, но надо обновлять компы и пересаживаться на Win7 хотя бы.

**Comment by zenden2k** [comment]
Посмотрел исходники Qt, там тоже используется WM_DRAWCLIPBOARD, хотя казалось для новых систем могли бы юзать более новые методы, рекомендуемые Microsoft.

**Comment by arhangelsoft** [comment]
Ога, Windows 98 шлет привет в тех. поддержку Qt.

**Comment by zenden2k** [comment]
@maxvlas Попробуйте новую сборку 1.3.2-alpha build 4446 (либо проверьте обновления)

http://zenden.ws/ru/imageuploader_downloads

Что нибудь изменилось? Какие-нибудь ошибки появляются в логе программы?

**Comment by arhangelsoft** [comment]
>oh shit, у меня github на windows xp не открывается)))) через ie

Зачем спрашивается? XP то ладно, а вот 6го осла всем интернетом ненавидят.

**Comment by zenden2k** [comment]
У меня 8-ой осел

**Comment by arhangelsoft** [comment]
На всякий запилите проверку на NULL для вызова GlobalLock, мало ли дедлок поставить не смогло по причинам из космоса.

**Comment by zenden2k** [comment]
>На всякий запилите проверку на NULL для вызова GlobalLock, мало ли дедлок поставить не смогло по причинам из космоса.
Если бы GlobalLock возвращал NULL, программа просто бы упала.

**Comment by maxvlas** [comment]
#Попробуйте новую сборку 1.3.2-alpha build 4446 (либо проверьте обновления)

http://zenden.ws/ru/imageuploader_downloads

Что нибудь изменилось? Какие-нибудь ошибки появляются в логе программы?
Попробовал 1.3.2-alpha build 4448
Копирует,то все нормально,повторно пробую для интереса,то нормально то ошибка вот такая
[url=http://fs2.directupload.net/images/150507/rfhjkarf.png][img]http://fs1.directupload.net/images/150507/g52vi7kw.png[/img][/url]  
После ошибки если продолжать копировать то она так и выдается ,пока отмена не нажмешь и по новой не начнешь

**Comment by zenden2k** [comment]
ERROR_ACCESS_DENIED
Это значит, что какая-то программа открыла буфер обмена и не закрыла его.

**Comment by maxvlas** [comment]
>maxvlas 
каким браузером вы пользуетесь? 
Какие еще программы запущены? 
Запустите программу clipbrd.exe и посмотрите, меняется ли текст в ее окне при копировании каждой ссылки.

1.Браузерами Гугл хром и мозила пробовал
2.Ничего не запущено,в трее только - **IDM,FSCapture,KeyScrambler Premium,Everything,Process Hacker,System Explorer,AnVir Task Manager.**
3.Запустил **clipbrd.exe** ,все ссылки такие же
http://fs2.directupload.net/images/150507/5flagvtp.png

>Это значит, что какая-то другая программа открыла буфер обмена и не закрыла его.
В **Image Uploader 1.3.1 build 4318 Portable** не было этого

**Comment by maxvlas** [comment]
**zenden2k**
Вообще то нашел причину,но как исправить не знаю
Все убрал короче из трея.
И вспомнил я же (запущен у меня) пользуюсь **Directory Opus** - https://www.gpsoft.com.au/
И вот сделал выход программе,попробовал ссылки копировать в **Image Uploader** (раз 10 пробовал),копирует нормально,а также и нет ошибок в последней альфе.
запустил вновь с ярлыка Directory Opus,тоже самое началось что и раньше
Выходит проблема при работе **Image Uploader** и **Directory Opus**
Но как и где это поправить?
Я давно **Directory Opus** пользуюсь,и без него ни куда,как и другие **Total Commander**
Я конечно с ярлыка запускаю его,жена не любит им пользоваться,я в настройках ничего не ассоциировал

**Comment by arhangelsoft** [comment]
Глобальные ловушки решили бы проблему :)

**Comment by zenden2k** [comment]
@maxvlas 
Какая версия Directory Opus? Я установил последнюю версию с сайта, 11.13 x86 build 5564, и у меня не воспроизводится ошибка.

**Comment by zenden2k** [comment]
@arhangelsoft 
>Глобальные ловушки решили бы проблему :)

Как бы  они решили проблему фейла `OpenClipboard` ???

**Comment by maxvlas** [comment]
Сейчас стоит **Directory Opus 11.13.1 (Beta)**,плагины не ставил никакие
Тут похоже дело не в версии Directory Opus,ранее у меня другая стояла и при копировании тоже проблемы наблюдались.
Я уже не раз писал,вот к примеру 2014 год http://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=880#7
**1.** Если запущен  **Directory Opus 11.13.1 (Beta)**
 - 1.3.2-alpha build 4448  Portable при копировании ссылок,то нормально копирует,то выдает вот такую ошибку
http://fs2.directupload.net/images/150507/rfhjkarf.png

**2.** Если запущен  **Directory Opus 11.13.1 (Beta)**
  - Image Uploader 1.3.1 build 4318 Portable при копировании ссылок,то нормально копирует все,то пропускает некотрые ссылки,не все берет.(но ошибка не вылазит как в alpha)

**3.** Если  **Directory Opus 11.13.1 (Beta)** Сделать выход
  - **Image Uploader 1.3.1 build 4318 Portable** и **Image Uploader 1.3.2-alpha build 4448 portable** пробовал по 10 попыток в каждой копировать,Все ссылки.все копирует без проблем
Ни разу,ни альфа ни стабле не ошиблись.

Из за чего это?,может на форуме  Directory Opus написать или в Image Uploader надо что то?

**Comment by zenden2k** [comment]
>(но ошибка не вылазит как в alpha)

Потому что там нет проверки ошибок.

Обновите IU сейчас до версии 1.3.2-alpha.4449, она должна выдать больше информации об ошибке.

**Comment by arhangelsoft** [comment]
> Как бы они решили проблему фейла OpenClipboard ???

Ловушки получают сообщение перед тем как их получит wndproc процесса куда загружена ловушка, в случае с глобальными, ловушка есть во всех процессах. А значит процесс Y не успеет залочить буфер до вас. Да по идее уже и не надо будет этого делать, прям оттуда и забирать.

поиграюсь сегодня на паскале с этим механизмом.

**Comment by zenden2k** [comment]
Я не хочу никуда внедрять dll, от этого будет больше вреда, чем пользы.

**Comment by arhangelsoft** [comment]
>Я не хочу никуда внедрять dll, от этого будет больше вреда, чем пользы.

а вам и не надо. Система сама этим занимается, вы всего лишь вызываете SetWindowHookEx внутри dll.

**Comment by zenden2k** [comment]
И так уже имею проблемы с ExplorerIntegration.dll, который система никак не хочет отпускать.

**Comment by arhangelsoft** [comment]
Расширения раб. стола там другое дело. Не отпускает потому с расширением что-то работает, а не расширение работет с чем-то. Во втором случае можно прекратить работать, в первом не получится.

**Comment by arhangelsoft** [comment]
А какие увас проблемы с отгрузкой расширения?

Там 2 пути:
Первый:
1. Убить процессы
2. Копирнуть dLL

Второй:
1. Не трогать процессы
2. Исп. MoveFileEx копирнуть файл с флагом замены после перезагрузки
3. Перезагрузить ПК.


Расширение задкйствует не только рабочий стол, но и осел, блокноты, да что угодно.

**Comment by zenden2k** [comment]
Проблемы в основном у меня при разработке, потому что у меня много разных версий, и в итоге может оказаться, что скажем в проводнике работает старая версия расширения, а в total commander-e  - новая. Возникает путаница.

**Comment by maxvlas** [comment]
Искал.вот что нашел:
**Вот здесь прочтите**,не знаю связано это или нет,может поможет
http://forum.ru-board.com/topic.cgi?forum=5&topic=17836&start=1620#9

**Comment by maxvlas** [comment]
>**zenden2k**
Обновите IU сейчас до версии 1.3.2-alpha.4449, новая версия должна выдать больше информации об ошибке.

**Image Uploader 1.3.2-alpha build 4449 portable**
Потестил при запущенном Directory Opus 11.13.1 (Beta)
:+1:  Ни каких ошибок,все ссылки копирует,и из поста выше пробовал и из яндекса картинки открыл, все подряд копировал,все скопировалось
http://fs2.directupload.net/images/150507/3xzjz6kl.png

**Comment by zenden2k** [comment]
Вот что `Sleep` животворящий делает)

**Comment by maxvlas** [comment]
**zenden2k** & **arhangelsoft** 
Пока все отлично,**БЛАГОДАРЮ** за помощь и поддержку.
Если что замечу напишу.
