### ISSUE TITLE
Проблема с заливкой формата .PNG на http://jpegshare.net/

### ISSUE THREAD

**Issue by maxvlas** [zenden2k/image-uploader#156]
**zenden2k**
Если есть возможность.можно как то поправить заливку изображений формата **.png** на http://jpegshare.net/ ?

Хостинг неплохой,долго хранит очень снимки,сколько не заливал ни одна не пропала еще.
**Но** есть небольшая проблема с заливкой изображений формата **.png**
Здесь писал ранее я http://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=680#13
И в поиске нашел немного информации всего,никто так и не брался поправить
**Вот посты:** 
http://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=580#5
http://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=580#8
http://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=580#11

и ошибка,ошибок много написало (на снимке последние только),все не копируются вместе.если надо могу все скопировать по отдельности
http://fs1.directupload.net/images/150507/587uqwxm.png

**На сайте есть поддержка .png** - http://jpegshare.net/project/
>О проекте:
Максимальный размер файла: 12 мегабайт
Срок хранения: вечно*
Разрешенные форматы для опубликования: JPG, JPEG, PNG, GIF

**Comment by zenden2k** [comment]
Исправлено, проверьте обновления
