### ISSUE TITLE
Отмена через Ctrl+Z сильно тормозит

### ISSUE THREAD

**Issue by phantasm** [zenden2k/image-uploader#158]
Если в редакторе нарисовать несколько элементов, и нажать Ctrl+Z, то редактор подвисает на несколько секунд. Если же делать отмену кнопкой в панели инструментов, всё ок

**Comment by zenden2k** [comment]
Не знаю, как воспроизвести.
Некоторые пользователи жалуются на тормоза в графическом редакторе, но с чем это связано,  так и не понял.

**Comment by zenden2k** [comment]
Проблема воспроизводится на Windows 7.
Слишком долго работает LoadKeyboardLayout().
Будет пофикшено в следующем билде.
