### ISSUE TITLE
Еще одно непереводимое сообщение

### ISSUE THREAD

**Issue by YuriPet** [zenden2k/image-uploader#162]
![bdxlkhw](https://cloud.githubusercontent.com/assets/11704993/7787852/18d662fa-022a-11e5-8103-727894b5afd2.jpg)

**Comment by zenden2k** [comment]
Вроде бы это исправлено.
В новой версии русский язык в исходниках был заменен на английский, а файлы переводов теперь в кодировке utf-8. Поэтому, в некоторых местах перевод может быть не совсем тем, который ожидается.
