### ISSUE TITLE
Data/Scripts побить на категории

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#164]
I'm back! 

Собственно может разбить в Data\Scripts все скрипты так же на под папки?
Imageupload
Fileupload
UrlShort

?

**Comment by zenden2k** [comment]
Нет, потому что один скрипт может сразу трех типов Imageupload
Fileupload
UrlShort

**Comment by arhangelsoft** [comment]
вопрос исчерпал себя.
