### ISSUE TITLE
HTML код не валидный

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#169]
Программа генерирует не валидный HTML код.
Нет атрибута alt
Убрать атрибут border
Убрать `<center>`

В первую очередь надо перейти к использованию OutputCodeGenerator вместо того ужаса, что сейчас есть

**Comment by zenden2k** [comment]
Также невалидный и в ZOutputCodeGenerator (CLI)

**Comment by arhangelsoft** [comment]
Предлагаю не хардкодить, а привязаться к шаблонам, заменяя паттерны на реальные данные.
От простого маппинга и замены подстроки в строке, типа [format от FaceBook](https://github.com/facebook/folly/blob/master/folly/docs/Format.md),
до нормального [шаблонизатора](https://github.com/hughperkins/Jinja2CppLight)

**Comment by zenden2k** [comment]
Не уверен, что это будет востребовано. По крайней мере, ко мне никто не обращался с просьбами по этому поводу.
Есть файл templates.xml, в котором можно задавать простейшие шаблоны.
