### ISSUE TITLE
Прошу добавить по возможности следующие хостинги - piccash.net

### ISSUE THREAD

**Issue by Syncronet** [zenden2k/image-uploader#173]
http://piccash.net/

**Comment by arhangelsoft** [comment]
Какой-то стремный хостинг. Написано "бесплатно", а намека на бесплатна там и нет. Только через регистрацию.

**Comment by zenden2k** [comment]
@arhangelsoft но ведь регистрация-то бесплатная :)

**Comment by zenden2k** [comment]
Этот хостинг я не буду добавлять. Читайте доки.
