### ISSUE TITLE
Исправьте, пожалуйста, заливку на imagebam.com

### ISSUE THREAD

**Issue by vkorone** [zenden2k/image-uploader#174]
сейчас (v 1.3.1 Build 4318) выдаются некорректные адреса. сервис очень нужный и надёжный!

**Comment by zenden2k** [comment]
Странно, у меня всё работает

**Comment by vkorone** [comment]
я не знаю почему, но у меня выдаёт только ссылки на загруженные картинки в таком виде:
![1](https://cloud.githubusercontent.com/assets/13608285/9088530/25367078-3b99-11e5-88b1-fb17136a233c.png)
![2](https://cloud.githubusercontent.com/assets/13608285/9088534/28f24b4c-3b99-11e5-8ab5-c8e88c1c7b88.png)
![3](https://cloud.githubusercontent.com/assets/13608285/9088538/30e963a8-3b99-11e5-8ceb-5b4e4cdc19d1.png)

**Comment by zenden2k** [comment]
В чем ошибка?  imagebam не дает прямые ссылки

**Comment by vkorone** [comment]
тогда вопрос снимается! я думал, что это ошибка...
