### ISSUE TITLE
добавьте пожалуйста static.md

### ISSUE THREAD

**Issue by drakulaboy** [zenden2k/image-uploader#175]
http://static.md/?lang=ru
От всей души прошу!

**Comment by zenden2k** [comment]
Комментарии для меня:

Этот хостинг требует обновлять токен каждые 30 секунд.
Не уверен насчет многопоточной загрузки.
Нужно синхронизировать токен, а API для межпоточной синхронизации пока еще не закончен.

**Comment by zenden2k** [comment]
@drakulaboy сейчас у меня в приоритете другие фичи, а не новые хостинги.

**Comment by arhangelsoft** [comment]
Перед загрузкой новый токен брать и решит проблему, не?

**Comment by zenden2k** [comment]
@arhangelsoft это замедлит загрузку, там требуется делать `sleep()` на несколько секунд после получения токена.

**Comment by zenden2k** [comment]
Хотя  я наврал, можно обойтись и существующим api:

```
Sync.beginAuth();
local token = Sync.getValue("token");
if ( token == "") {
 // получение токена 
Sleep(3000);
}
Sync.endAuth();

// аплод файла
```

**Comment by zenden2k** [comment]
Короче этого сайта в программе не будет.
