### ISSUE TITLE
Crash with environment variable (percent symbol - %) in path to external editor

### ISSUE THREAD

**Issue by m-alice** [zenden2k/image-uploader#176]
Open "Program Settings";
In "General" tab write any %%-path in "Images editor" (e.g. %temp%);
Apply, open random image and press "Open in external editor" menu.

**Comment by zenden2k** [comment]
Thank you for reporting.
This bug has been fixed in the 1.3.2 branch. A new build will soon be available.

**Comment by m-alice** [comment]
thx
