### ISSUE TITLE
Указывать какие расширения поддерживают хостинги картонок

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#178]
Собственно в servers.xml завести атрибут exts="" для type="image", в котором перечисляются через запятую, расширения, которые поддерживает конкретный хостинг картинок. 

По расширения файла выдавать на выбор естественно те хостинги, которые поддерживают указанный формат. 

Аргументирование: Image Uploader ну вот совсем никак не помог мне загрузить gif на хостинг. Вся прелесть в том что, все фото-хосты поддерживают gif вот таким образом: вырезают первый фрейм и считают, что успешно загрузили картинку.

**Comment by zenden2k** [comment]
Да ладно? прям все?

http://fs2.directupload.net/images/150814/bkn6nsxr.gif

**Comment by zenden2k** [comment]
А не дубликат ли это
https://github.com/zenden2k/image-uploader/issues/74

**Comment by zenden2k** [comment]
И скорее всего это сама программа оставляет один фрейм. Она не умеет работать с анимацией.

**Comment by arhangelsoft** [comment]
> Да ладно? прям все?

На 5-м хостинге я остановился, и пошел искать правильный хостинг в гугле :(
Из чего и сделал вывод, либо ПО само gif'ки не поддерживает, либо не поддерживает хостинги, которые умеют обращаться с gif.

> А не дубликат ли это
Оно самое :)

**Comment by zenden2k** [comment]
Закрываю как дубликат
