### ISSUE TITLE
Еще один сервис сокращения ссылок - vk.cc

### ISSUE THREAD

**Issue by zihiwoz** [zenden2k/image-uploader#179]
Добавьте, пожалуйста, такой сервис сокращения ссылок как http://vk.com/cc
Часто пользуюсь програмой для публикации скриншотов в вконтакте. И у меня в настройках был выбран сервис u.to из-за этого страница была заморожена на сутки. В тех. поддержке ответили, что это из-за сервиса сокращения ссылок. Позже изменил на goo.gl и опять заморозили.
Агент поддержки ответил, что если использовать сокращение ссылок http://vk.com/cc , то заморозок можно будет избежать.

**Comment by zenden2k** [comment]
vk.cc требует авторизации и не имеет публичного API

**Comment by vladios13** [comment]
Хотел утром еще предложить этот сервис. Но увы

**Comment by zenden2k** [comment]
Добавлен.
