### ISSUE TITLE
Отображать прогресс при аплоде из трея

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#180]
Сейчас совершенно непонятно, идет загрузка на сервер или нет. Balloon отображается через раз или слишком быстро пропадает.
Думаю, стоит сделать анимацию иконки или маленькое окошко с прогрессом.

**Comment by vladios13** [comment]
Да было бы отлично!)

**Comment by zenden2k** [comment]
![iu_animation.gif](https://lh3.googleusercontent.com/-AEplm92Ne4I/Vd7fJP4B77I/AAAAAAAAF8w/P-YnM83IqSk/s0/iu_animation.gif)

**Comment by zenden2k** [comment]
Пока этого хватит.

**Comment by vladios13** [comment]
Шикарно! zenden2k
