### ISSUE TITLE
Copy image to the clipboard in data:uri format / Копировать в буфер в формате data:image

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#181]
>data man
Отправлено: 15:15 26-08-2015

Просьба добавить кнопку "Копировать в буфер в формате data:image"
https://ru.wikipedia.org/wiki/Data:_URL

- Добавить кнопку в редактор изображений
- Вложенное меню "Копировать как ..." -> "В формате data:uri" в контекстное меню списка картинок

**Comment by arhangelsoft** [comment]
+ в формате HTML. <img src="data:image/png;base64" alt="описание"/>

**Comment by zenden2k** [comment]
Надо еще конвертировать картинки в не-веб формате в какой-то формат, но это потом сделаю
