### ISSUE TITLE
Каким хостингом загрузки пользуетесь вы?

### ISSUE THREAD

**Issue by zihiwoz** [zenden2k/image-uploader#183]
Всем привет.
Лично я пока что остановился на imageban.ru. 
Для меня важно чтобы:
1. я имел доступ к скриншотам с пустя какое-то время;
2. удаляя скриншот с сервиса, он моментально переставал быть доступен по упубликованной мною ссылке;
3. сами скриншоты публиковались закрыто и были доступны только тем, кому я дал на них ссылку.

Первым двум imageban.ru соотвествует, а вот по поводу третьего вот что я заметил. Сделав скриншот и нигде не публикуя ссылку в аккаунте сервиса показало, что на скриншот перешло два человека. 
В самом сервисе сайта есть функция создания скрытых альбомов, но Image Uploader туда их не льет. Это можно поправить?

И быть может есть вариант другого сервиса, который соотвествует трем требованиям?

**Comment by zenden2k** [comment]
Я пользуюсь Picasa WebAlbums, но он не удовлетворяет пункту 2.

**Comment by vladios13** [comment]
Пользуюсь я VK, но он также не удовлетворяет пункту 2. Хотя для это я создал совой фотохост с блэкджеками и ... Мне удобно!  (imgice.ru)
