### ISSUE TITLE
Проблема при заливке на http://simplest-image-hosting.net/

### ISSUE THREAD

**Issue by maxvlas** [zenden2k/image-uploader#192]
При заливке на http://simplest-image-hosting.net/ проблемы
Заливает,если стоит галка "Использовать серверные миниатюры"
http://s1.bild.me/bilder/030315/65111242015-10-08_193822.png

[URL=http://simplest-image-hosting.net/jpg-0-09-05-26-18-31-23samarkand-0311][IMG]http://i0.simplest-image-hosting.net/thumbnail/09-05-26-18-31-23samarkand-0311.jpg[/IMG][/URL]
[URL=http://simplest-image-hosting.net/jpg-0-09-05-27-09-00-57samarkand-0344][IMG]http://i0.simplest-image-hosting.net/thumbnail/09-05-27-09-00-57samarkand-0344.jpg[/IMG][/URL]

Вот что получается если галка не стоит:
[url=http://6g6.eu/sih0-04-.jpg]04.Куликалонские озера с пер.Лаудан..jpg[/url]  [url=http://6g6.eu/sih0-10-0.jpg]10.Вершина Чапдара и Алаудинские озера.jpg[/url]  [url=http://6g6.eu/sih0-01-.jpg]01.Долина реки Варзоб.jpg[/url]  [url=http://6g6.eu/sih0-02-0.jpg][img]http://i0.simplest-image-hosting.net/thumbnail/02-0.jpg[/img][/url]  [url=http://6g6.eu/sih0-03-.jpg]03.Тропа на перевал Лаудан..jpg[/url]  

Можно как то поправить,чтоб заливка происходила как и на другие хостинги,чтоб лишний раз не лазить в настройки

**Comment by zenden2k** [comment]
поправим

**Comment by maxvlas** [comment]
Благодарю за помощь,работу,и поддержку

**Comment by zenden2k** [comment]
Этот сервер не поддерживает прямые ссылки, поэтому можно использовать только "серверные миниатюры". Надо об этом как-то предупреждать пользователя.

**Comment by zenden2k** [comment]
Однако мне не удалось добиться такого результата, как у вас. При любых настройках у меня получается так:

```
[url=http://6g6.eu/sih0-screenshot-2015-11-07-003.png][img]http://i0.simplest-image-hosting.net/thumbnail/screenshot-2015-11-07-003.png[/img][/url]  
```

**Comment by zenden2k** [comment]
Умер
