### ISSUE TITLE
Сделать возможность сохранения курсора на экране, с сохранением фокуса.

### ISSUE THREAD

**Issue by Zelgadiss** [zenden2k/image-uploader#208]
Иногда требуется снимать выпадающие по ховеру меню. И если делать снимок области, то теряется фокус с меню и оно исчезает. Неплохо бы это пофиксить.

**Comment by zenden2k** [comment]
Какая операционная система?
Скриншот делаете с помощью горячей клавиши?

**Comment by zenden2k** [comment]
У меня меню наоборот, не пропадает, а оказывается поверх редактора изображений.
Пропадает меню только в браузере гугл хром.

**Comment by Zelgadiss** [comment]
Операционная система Windows 7 x64 Enterprise
Да, либо с помощью PrintScreen, либо с помощью PrintScreen+Ctrl

С ув. Степан

26 ноября 2015 г., 16:17 пользователь zenden2k <notifications@github.com>
написал:

**Comment by zenden2k** [comment]
Исправлено в коммите https://github.com/zenden2k/image-uploader/commit/ccadf18c448f762da17bb660357f19feaa8b3c41
