### ISSUE TITLE
Перевести проект на cmake, разбить на библиотеки

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#215]
Разбить на некоторое количество библиотек

iuCore - Всякие штуки для работы с файлами, костыли
iuNetwork -  NetworkClient (нужно ли?)
iuTransfer - upload/download
iuMultimedia - работа с видеофайлами
iuScreenshot - создание скриншотов и всё что с этим связано
iuImage - обработка изображений
iuImageEditor - редактор изображений
...

**Comment by arhangelsoft** [comment]
Такое нужно, когда одну библиотеку использует несколько программ, и у вас нет доступа/средств к коду другой программы, т.е. вы пишите только библиотеку.

У вас же, просто каша в коде. Куча разношерстных классов в одном файле, которые используются черт-знает-каким количеством пусковых файлов, при этом все эти пусковые надо пересобирать при изменении класса. 

Скажем так, вытяните в отдельную библиотеку(и) код, который действительно используется несколькими программами, таким образом исправляя баг в библиотеке, не потребуется пересобирать пусковые бинарники. Обновили dll, перезапустили процесс -  используем новую версию! Профит.

**Comment by zenden2k** [comment]
да. будет несколько программ

**Comment by zenden2k** [comment]
В итоге я создал несколько подпроектов CMake для Core/CLI/ServersChecker/Tests, но саму программу пока не перевел на CMake.

**Comment by zenden2k** [comment]
Проект переведен на CMake, кроме ShellExt (расширение для проводника).
