### ISSUE TITLE
OAuth авторизация с помощью встроенного веб-сервера

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#219]
Начиная с версии 1.3.2 в программу встроен маленький веб-сервер.
Думаю, стоит перейти на авторизацию посредством перехода на адрес http://localhost:port/something, что поддерживают OAuth 2 серверы, вместо копирования кода вручную.

**Comment by vladios13** [comment]
Шикарно! А использоваться на какие хостинга такие как vk?

**Comment by zenden2k** [comment]
Нет, vk стоит особняком, это для picasa, google drive, yandex,

**Comment by vladios13** [comment]
Понял, спасибо. Когда ждать релиз?

**Comment by zenden2k** [comment]
@vladios13 
На осень лет через восемь))

**Comment by vladios13** [comment]
Понял.

**Comment by zenden2k** [comment]
Хотелось бы также сделать, чтобы работала авторизация на linux-серверах без gui:

![](http://fs5.directupload.net/images/151210/5u7aprqk.png)

**Comment by arhangelsoft** [comment]
Тогда уж Chromium Embedded Framework, там и Linux есть :)

**Comment by zenden2k** [comment]
ээээ и как это сделать

**Comment by zenden2k** [comment]
про линукс я не понял

**Comment by arhangelsoft** [comment]
Можно начать отсюда https://bitbucket.org/chromiumembedded/cef/wiki/Tutorial#markdown-header-linux

**Comment by arhangelsoft** [comment]
Расписан процесс работы фреймворка, даны простые примеры под Win, Linux, MacOS и шаги по сборке.

**Comment by zenden2k** [comment]
В общем можно поднимать веб-сервер из .nut скриптов
