### ISSUE TITLE
Автоматическое переключение опции "Использовать прямые ссылки"

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#222]
На некоторых серверах основными являются не прямые ссылки, а ссылки на страницу просмотра.
По крайней мере, это касается Google Drive. Однако с Google Drive можно встраивать картинки. Надо придумать, как это разрулить. 

http://forum.vgd.ru/2125/72477/

**Comment by arhangelsoft** [comment]
На всккидку так:
Делаем запрос на http://i63.tinypic.com/n569w5.jpg если ответ не image/png то это ещё не прямая ссылка. Делаем запрос содержимого, ищем там n569w5.jpg, если найдено в атрибуте href или src то это прямая ссылка. 

Но массово это не обойти, так, для каждого случая свой способ. Хотя возможно и прокатит.
