### ISSUE TITLE
Отображение горячих клавиш, у кнопок в трее.

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#235]
Собственно подзабыл некоторые комбинации которые редко использую, но в трее есть "Сделать скрин прямоугольной области", в настройках есть опция хоткея для этой кнопки.

Надо бы на этой кнопке в трее, хоткей рисовать.

**Comment by zenden2k** [comment]
имеется в виду меню значка в трее?

**Comment by arhangelsoft** [comment]
Да.
http://i.imgbox.com/ZW3anh4p.png

http://i.imgbox.com/lBfllfMV.png

**Comment by zenden2k** [comment]
Хорошо, будет, когда будут силы
