### ISSUE TITLE
не загружается на imgur

### ISSUE THREAD

**Issue by fnqmaobd** [zenden2k/image-uploader#237]
В версии 1.3.2-alpha перестали загружаться скриншоты на imgur.
Долго крутится, а потом выдает такое:
http://fs5.directupload.net/images/160226/6iripzw6.jpg

**Comment by zenden2k** [comment]
Не могу воспроизвести этот баг

**Comment by arhangelsoft** [comment]
@fnqmaobd fixed there #245
