### ISSUE TITLE
Fastpic.ru, ImabeBam.com, ImageVenue.com

### ISSUE THREAD

**Issue by GitHubHipster** [zenden2k/image-uploader#238]
Вот эти хосты не работают. Пожалуйста почините!:

1.

> imgupload.exe -s fastpic.ru -cl plain -ct Images 

Нечего не возвращает.

2.

> imgupload.exe -s imagebam.com -cl bbcode -ct ClickableThumbnails
> imgupload.exe -s imagevenue.com -cl bbcode -ct ClickableThumbnails

Возвращает:

> [url=][img]http://thumbnails114.imagebam.com/111.jpg[/img][/url]

Обратите внимание на пустое УРЛ.

Спасибо

**Comment by GitHubHipster** [comment]
Ваш код единственный в интернете который работает с fastpic.

Зенден2000, пожалуйста почините!

**Comment by arhangelsoft** [comment]
Please, include version of Image Uploader that yoy use.
Пожалуйста, пишите версию программы когда речь идет о скриптах поддержки различных хостингов изображений.

**Comment by GitHubHipster** [comment]
Hello ArchangelSoft

I am using the latest version: `imgupload_0.2.5_win32`

Я использую самую новую версию: `imgupload_0.2.5_win32`

**Comment by arhangelsoft** [comment]
@GitHubHipster починю, релиз будет в моём форке ImageUploader'а. Прикрепите куда-нибудь imgupload_0.2.5_win32, у меня её нет. Оф. сайт лежит.

**Comment by GitHubHipster** [comment]
https://github.com/GitHubHipster/ZendenImgUpload

У меня исходников нет :( . Только уже исполняемые файлы.
