### ISSUE TITLE
imgur no longer uploading

### ISSUE THREAD

**Issue by lonku** [zenden2k/image-uploader#239]
This is the error message it now gives:

---

E0402 00:48:17.028003  8696 NetworkClient.cpp:434] Request to the URL 'http://imgur.com/api/upload.xml' failed.
Response code: 404

Server: imgur.com(CDefaultUploadEngine)
URL: http://imgur.com/api/upload.xml
Action: #2
Server response code: 404

---

File: .\b88f06dad51a5ba1bd12eff4ba8cfa44.jpg
## Upload failed. Another retry (2)

E0402 00:48:17.433315  8696 NetworkClient.cpp:434] Request to the URL 'http://imgur.com/api/upload.xml' failed.
Response code: 404

Server: imgur.com(CDefaultUploadEngine)
URL: http://imgur.com/api/upload.xml
Action: #2
Server response code: 404
## retrying... (2 of 2)

E0402 00:48:17.848569  8696 NetworkClient.cpp:434] Request to the URL 'http://imgur.com/api/upload.xml' failed.
Response code: 404

Server: imgur.com(CDefaultUploadEngine)
URL: http://imgur.com/api/upload.xml
Action: #2
Server response code: 404

---

File: .\b88f06dad51a5ba1bd12eff4ba8cfa44.jpg
## Upload failed! (retry limit reached)

Unable to upload file!

Result:

**Comment by Fironet** [comment]
I've been getting error this for about a week. Imgur seems to have changed something.

**Comment by arhangelsoft** [comment]
Did you use beta-version or stable?

**Comment by lonku** [comment]
I'm using the console utility v0.2.5 (based on IU v1.3.1 build 4318)

**Comment by ZackBoe** [comment]
Just want to chime in that I'm using a unrelated shell script (found this thread on Google) to upload images and have been seeing the same error during the last week. I've reached out to Imgur and will provide an update if I get a response.

**Comment by Fironet** [comment]
> I've reached out to Imgur and will provide an update if I get a response.

Looks like some API change, which is super annoying. More interestingly when the Image Uploader error occurs the mobile USB device I sometimes use disconnects.

Really hope someone can look into this, as it was of of my most used daily tools and a great program.

**Comment by ZackBoe** [comment]
Sorry for not updating earlier. Imgur wasn't very helpful, simply stating that they've discontinued v1 & v2 of their API. I've not been able to find this _anywhere_ on their site or documentation. Here's their response: 

> Thanks for contacting Imgur Help! To help you as quickly as possible, we've detected that you might have a question about our API. Full documentation on the Imgur API, pricing, and performance tips can be found at api.imgur.com.

> 
Versions 1 and 2 of our API have recently been depreciated to allow for better features and advancements in version 3. Anything using version 1 or 2 will need to upgrade to version 3. Unfortunately we’re unable to provide personal support on API related questions at this time, but we encourage you to head over to the Imgur API Google Group to connect with other developers using the API. (https://groups.google.com/forum/?fromgroups#!forum/imgur)

**Comment by ZackBoe** [comment]
Because of this change, a great deal of the extensions, apps, and scripts they themselves feature on [imgur.com/tools](http://imgur.com/tools) are now no longer functional.

**Comment by Fironet** [comment]
Cheers for the quoted response. Looking at that Groups link it seems there are half a dozen threads about it but few replies. Very helpful on their part :p It's odd they'd just up and change it without notice.

**Comment by Fironet** [comment]
@zenden2k can you reproduce this issue?

In the meantime I tried using the IU Helper tool but since the imgur.com site uses Javascript for its buttons I didn't have any luck creating a custom server. Been months since I've been able to use Image Uploader with Imgur :sob:

**Comment by arhangelsoft** [comment]
@Fironet  @ZackBoe @lonku watch fix here #245
