### ISSUE TITLE
Urlshortening

### ISSUE THREAD

**Issue by oompaloomp** [zenden2k/image-uploader#248]
Добрый день,
возможно ли добавить в функционал коротких ссылок ресурс bit.do с возможностью авторизации.
Спасибо

**Comment by arhangelsoft** [comment]
Пока что могу сказать, что пользовательскую часть они очень хитрожопо сделали (т.е. просто эмитировать запрос к сервису - это не работает), не смотря на убогость дизаина уровня "2000 год, windows 98", не говоря уже про то, что все это на perl-скриптах.
Авторы изобретательны, но накурены конкретно.


P.S. Для сервисов сокращения ссылок пока не возможности использовать авторизацию. Даже в бета-версии 1.3.2

**Comment by oompaloomp** [comment]
arhangelsoft, ясно
спасибо за оперативный ответ.

**Comment by arhangelsoft** [comment]
Думаю вам лучше поискать другой сервис, благо их много) этот можно добавить но только без авторизации, и он будет работать только на windows (будет использоваться интегрируемый браузер IE, что бы все работало "как надо". Но проще использовать другой сервис, этот очень медленно работает.

**Comment by oompaloomp** [comment]
Ок, будем посмотреть =)
