### ISSUE TITLE
Use last crop area

### ISSUE THREAD

**Issue by hardway777** [zenden2k/image-uploader#249]
In some cases need to reuse last crop area for take screenshots with same size or one area. In this case program can save last crop area and show it if crop tool is selected.

В некоторых случаях необходимо повторно использовать последнюю обрезанную область для создания скриншотов такого же размера или одной и той же области. В этом случае программа может сохранить последнюю область обрезки и показать её, если выбран инструмент обрезки.

**Comment by zenden2k** [comment]
В следующем релизе будет возможность сделать снимок последней выбранной области.
Пока эта функция доступна только в [Nighly build](http://zenden2k.com/ru/imageuploader_nightly).

![screenshot 2019-08-15 001](https://user-images.githubusercontent.com/2940480/63109812-aff96b80-bf92-11e9-9ad3-82908c586ec3.png)
