### ISSUE TITLE
Добавить хостинг картинок

### ISSUE THREAD

**Issue by Podpizdun** [zenden2k/image-uploader#250]
Можно ли Добавить хостинг картинок http://picimage.net

**Comment by arhangelsoft** [comment]
Маловероятно, сайт использует Flash для загрузки картинок.

**Comment by zenden2k** [comment]
https://github.com/zenden2k/image-uploader/commit/3f5e139d302903cdb244a11588421eabd7f28e92#diff-a6d06f2c0e5995386ffabcef151a7cdb
