### ISSUE TITLE
Переписать утилиту на nwjs?

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#251]
доброго времени, 

есть идея: 
А что если переписать утилиту на nwjs.io?

Плюсы:
 - можно использовать всю мощь веб-браузера: HTML5, CSS3, JavaScript.
 - кросс. платформенность с интерфейсом.
 - Отдельный скрипт. движок больше не нужен.
 - Если нужна консольная версия, то тот же код, просто исп. файл другой.

**Comment by zenden2k** [comment]
Ну и какие преимущества это даст, помимо интерфейса?
Тем более писать на javascript то еще удовольствие.
Я бы на Qt переписал интерфейс, если бы обладал бесконечным временем и силами.
Но это огромный объем работы. 

Сейчас есть некоторое ядро программы, которое относительно кроссплатформенное (может быть собрано для Linux и OS X). Но всё что связано со скриншотами, обработкой изображений, графический редактор совершенно не кроссплатформенные.
