### ISSUE TITLE
Yandex Disk upload problem

### ISSUE THREAD

**Issue by zhukovsergey** [zenden2k/image-uploader#252]
Hello. Apparently Yandex Disk was changed their API. I try to upload an image through Image Uploader and got infinity uploading process and I can't cancel it.

**Comment by Lexans** [comment]
Actual fixed version of yandex disk module
[yandexdisk.zip](https://github.com/zenden2k/image-uploader/files/923538/yandexdisk.zip)

**Comment by zenden2k** [comment]
Seem to be fixed
