### ISSUE TITLE
Что будет дальше с программой?

### ISSUE THREAD

**Issue by zihiwoz** [zenden2k/image-uploader#255]
Добрый день.
Сегодня узнал, что у автора программы проблемы со здоровьем и он больше не занимается поддержкой. 
Сергею желаю скорейшего выздоровления!

Image Uploader потихоньку начинают ломаться функции. С ядиска не приходит ссылка при загрузке файла и программа вылетает. Сокращение ссылки на скриншот иногда тоже приводит к зависанию программы. 
Насколько я понимаю, программа с открытым исходным кодом, кто-то еще занимается ее поддержкой?
Или может есть какие-то аналоги?

**Comment by arhangelsoft** [comment]
Я занимаюсь доработкой скриптов, когда на то есть время. Увы, у меня нет прав принимать пул-запросы. Ровно как и создавать обновления.

**Comment by ABTOP55** [comment]
@zihiwoz, подкорректируй, пожалуйста скрипт для rghost.ru

**Comment by arhangelsoft** [comment]
@zihiwoz Поправленные скрипты можно забрать тут [latest release](https://github.com/arhangelsoft/image-uploader/releases/latest)
