### ISSUE TITLE
Добавление сервера picabox.ru

### ISSUE THREAD

**Issue by kctrud** [zenden2k/image-uploader#256]
Добрый день хотим добавить сервер, проект жив?

**Comment by arhangelsoft** [comment]
Что за сервер, добавлю, только документацию по API дайте)

**Comment by kctrud** [comment]
Супер!
Сайт http://picabox.ru/
API http://picabox.ru/site/api
Если будут сложности пишите, всё решим. )

**Comment by arhangelsoft** [comment]
@kctrud не работает ваше API.
Посылаю POST запрос на http://picabox.ru/image/upload параметром:
ImagesForm[imageFiles][] и указанием файла.

В ответ код 200 и пустой ответ.

**Comment by arhangelsoft** [comment]
Разобрался, ошибка документации. ImagesForm[text] тоже обязателен.

**Comment by arhangelsoft** [comment]
Добавил picabox.ru

**Comment by kctrud** [comment]
Спасибо! Огромное! От всех наших пользователей! И от меня лично!

За косяк, сорь. Поправим. )

**Comment by kctrud** [comment]
Когда кстати можно им будет обновление загрузить?

**Comment by arhangelsoft** [comment]
@kctrud  с этим проблематичнее, #255.  
Автор ПО на не определенное время не занимается программой. По-скольку автор очень давно не актуализировал описания процесса сборки исходного кода, это приходится делать почти в слепую, и пока что не особо успешно получается, собрал нормально пару библиотек, с остальными колупаюсь.

Далее т.к. zenden.ws так же не работает, то не работает и автомат. обновление программы и скриптов, и скорее всего, их нужно будет брать вручную с моего форка image uploader'а.

**Comment by arhangelsoft** [comment]
@kctrud Fixed in my [latest release](https://github.com/arhangelsoft/image-uploader/releases/latest)

**Comment by kctrud** [comment]
Спасибо!

**Comment by kctrud** [comment]
[picabox.ico.zip](https://github.com/zenden2k/image-uploader/files/695305/picabox.ico.zip)
А вот и иконка! )

**Comment by zenden2k** [comment]
Сервер был добавлен
