### ISSUE TITLE
Подправьте, пожалуйста скрипт для загрузки файлов на rghost.ru

### ISSUE THREAD

**Issue by ABTOP55** [zenden2k/image-uploader#257]
Подправьте, пожалуйста скрипт для загрузки файлов на rghost.ru

**Comment by arhangelsoft** [comment]
@ABTOP55 Fixed in my [latest release](https://github.com/arhangelsoft/image-uploader/releases/latest)

**Comment by ripton07** [comment]
Поддерживаю!!!!

**Comment by arhangelsoft** [comment]
@ripton07 все уже пофикшено, лежит в моём форке проекта в релизах.

**Comment by ripton07** [comment]
Круто, Спасибо!!!
