### ISSUE TITLE
http://zenden.ws expired

### ISSUE THREAD

**Issue by refack** [zenden2k/image-uploader#259]
I use the app every day. I'm willing to donate one year domain and hosting 👍

**Comment by arhangelsoft** [comment]
@refack 
Hello, It seems to the project maintainer currently are not working on his project. 

But, you can watch my fork https://github.com/arhangelsoft/image-uploader
Sometimes I've publish hosting support scripts, also development are planned.

**Comment by refack** [comment]
Following you @arhangelsoft ...
