### ISSUE TITLE
Крайне не хватает возможности скопировать hex-код цвета с точке на экране или хотя бы с созданного скриншота.

### ISSUE THREAD

**Issue by MariaLovesGithub** [zenden2k/image-uploader#261]
К сожалению в графическом редакторе программы нет возможности ни скопировать hex-код цвета взятый пипеткой, ни добавить его вручную. Да и вообще редактор сильно ограничен, вот если бы вы добавили возможность использования стороннего редактора на не сохраненном скрине как например в Faststone Capture было бы здорово.

**Comment by zenden2k** [comment]
В следующем релизе будет возможность получить код цвета.
Пока эта функция доступна только в [Nighly build](http://zenden2k.com/ru/imageuploader_nightly).

![screenshot 2019-08-15 19-15-28 001](https://user-images.githubusercontent.com/2940480/63109194-4a58af80-bf91-11e9-9ecd-09fc5f6c024b.png)
