### ISSUE TITLE
не заливает и не может подключиться к yandex disk

### ISSUE THREAD

**Issue by winboard** [zenden2k/image-uploader#264]
1.3.1 (build 4318)
не заливает и не может подключиться к yandex disk
 
Существует решение?
yandexdisk.nut устарел, как я понимаю?

**Comment by ErikPshat** [comment]
@winboard да не переживайте так сразу. Вчера я видел на Яндекс Диске сообщение о технических работах. Возможно они ещё не завершены, поэтому загрузка не происходит. Подождите немного, проверьте свой диск на яндексе, наверняка заработает самом собой, если они там не изменили движок по заливке.

**Comment by winboard** [comment]
спасибо за ответ.
позже проверю)

**Comment by zenden2k** [comment]
Проблема еще актуальна?
