### ISSUE TITLE
Не отправляются скриншоты на сервер dropbox

### ISSUE THREAD

**Issue by userlond** [zenden2k/image-uploader#269]
При загрузке скриншота на dropbox программа во всплывающем окне логов ошибок пишет:
```
[16:16:07] 
NetworkClient.cpp:434

Request to the URL 'https://api.dropbox.com/1/shares/sandbox' failed. 
Response code: 400

{"error": "v1_retired"}
```

Ошибка связана с прекращением поддержки первой версии апи Dropbox.

Гайд по миграции: https://www.dropbox.com/developers/reference/migration-guide

Новость об отключении: https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/

**Comment by zenden2k** [comment]
Исправлено в новой сборке(4526)
http://zenden2k.atwebpages.com/ru/imageuploader_downloads
Теперь авторизация на дропбокс через встроенный браузер. На ХР работать не будет.
