### ISSUE TITLE
Не отправляются скриншоты на фотохостинг hostingkartinok.com

### ISSUE THREAD

**Issue by userpaint** [zenden2k/image-uploader#270]
Стоит стабильная версия 1.3.1 (build 4318). Не заливает и не может подключиться к фотохостингу [hostingkartinok.com](hostingkartinok.com).

**Comment by zenden2k** [comment]
попробуйте версию 1.3.2
http://zenden2k.atwebpages.com/ru/imageuploader_downloads
версия 1.3.1 больше не будет обновляться
