### ISSUE TITLE
Имея изображение разрешение которого выше чем твоего экрана, то оно не влезает в редактор

### ISSUE THREAD

**Issue by EngineExt** [zenden2k/image-uploader#276]
Имея разрешение экрана 1920х1080 открываем в редакторе изображение к примеру 3840х1082, и в редакторе мы не видим границ, ничего для его перетаскивания.
https://youtu.be/FKRakuZmrDE

**Comment by zenden2k** [comment]
Странно. У вас два монитора? 
Я пробовал повторить такое у себя, и у меня открывается окно с полосами прокрутки(скроллбарами)

**Comment by EngineExt** [comment]
> Странно. У вас два монитора?
Да их у меня 3 штуки,
Они расставлены не в клонировании а в продолжении рабочего стола.
При имении больше 1 монитора нужно показывать редактор на том где открыта программа, и показывать скроллбары, а можно же ещё лучше чтобы изображение работали ХотКеи как в Фотошопе, Альт+Колёсико и уменьшается масштаб или увеличивается

**Comment by zenden2k** [comment]
Я подумаю, что можно сделать. Добавить масштабирование мне будет тяжеловато.
Редактор довольно примитивен, но он никогда не задумывался как замена полноценному редактору, даже Paint-у. Быстро сделать какие-то пометки, не более того.

**Comment by EngineExt** [comment]
>Редактор довольно примитивен, но он никогда не задумывался как замена полноценному редактору, 

Он меня полностью устраивает своей примитивностью, кроме случая описанного выше и зависания во время сохранения(когда жму сохранить).
Спасибо что не бросил своё творение.

**Comment by zenden2k** [comment]
Теперь (в следующей версии) редактор будет открываться на весь экран, только если размеры изображения полностью совпадают с размером виртуального экрана (совокупности всех мониторов).
Во всех остальных случаях будет окно с прокруткой.

**Comment by zenden2k** [comment]
Еще актуально?

**Comment by EngineExt** [comment]
> Еще актуально?

Не скажу поскольку сижу на версии 1.3.1 :(

**Comment by EngineExt** [comment]
Вероятно пофикшено.

**Comment by arhangelsoft** [comment]
Не актуально.
В b4652 есть ползунки:
![image](https://user-images.githubusercontent.com/10620040/49368590-22296900-f700-11e8-91d9-cd6698516c03.png)
