### ISSUE TITLE
Не происходит автоматическое копирование ссылки

### ISSUE THREAD

**Issue by BlagoYar** [zenden2k/image-uploader#278]
В "_Настройки программы-Загрузка_" галочка на "_Автоматически копировать результаты в буфер обмена_" - установлена.
При загрузке файла через меню "_Отправить в ..._" с аргументами "_/fromcontextmenu /upload_" программа загружает файл на сервер, но не копирует ссылку автоматически. Но если перейти на любую вкладку ("_Для сайта_" или "_Для форума_"), то автокопирование происходит. 
**Image Uploader 1.3.2-alpha Build 4576**

**Comment by zenden2k** [comment]
Должно работать в последнем билде
