### ISSUE TITLE
https://prntscr.com

### ISSUE THREAD

**Issue by Dmitriandr** [zenden2k/image-uploader#279]
Здравствуйте. Добавьте пожалуйста возможность загрузки картинок на сайт: https://prntscr.com

**Comment by zenden2k** [comment]
Хорошо, постараюсь

**Comment by Dmitriandr** [comment]
Спасибо. И ещё добавьте заодно пожалуйста сайт по сокращению ссылок: https://bitly.com/ Желательно с авторизацией. Я частенько им пользуюсь. Но хотелось бы чтобы он был в этой программе.

**Comment by Dmitriandr** [comment]
Спасибо. А как сделать готовый скрипт к программе? Я скопировал весь код в блокнот и сохранил его с расширением .nut. Но Image Uploader не видит этого сайта.

**Comment by Dmitriandr** [comment]
Спасибо!

**Comment by Dmitriandr** [comment]
На https://prntscr.com/не загружает. Выдаёт ошибку:
```
[04:19:37] Файл: FileUploadTask(D:\Аватарки\С днём  рождения!.jpg)
Сервер: prntscr.com(CScriptUploadEngine)
Модуль загрузки

CScriptUploadEngine::uploadFile
the index 'GetImageInfo' does not exist

[04:19:37] Файл: FileUploadTask(D:\Аватарки\С днём  рождения!.jpg)
Сервер: prntscr.com(CScriptUploadEngine)
Модуль загрузки

prntscr.nut [Task=FileUploadTask(D:\Аватарки\С днём  рождения!.jpg), ThreadId=2508]

AN ERROR HAS OCCURED [the index 'GetImageInfo' does not exist]

CALLSTACK
*FUNCTION [UploadFile()] prntscr.nut line [7]

LOCALS
[hash] "47c29fca9a8f0ae744ed7fe839ea35b6"
[tm] "1539307177"
[mime] ""
[name] "С днём  рождения!.jpg"
[options] INSTANCE
[FileName] "D:\Аватарки\С днём  рождения!.jpg"
[this] TABLE

[04:19:37] Файл: D:\Аватарки\С днём  рождения!.jpg
Модуль загрузки

Загрузка не сервер удалась! (лимит попыток исчерпан)
```

**Comment by zenden2k** [comment]
Этот скрипт зависит от новой функции GetImageInfo, которая недоступна в старой версии программы.
Дождитесь, пока я выпущу новый билд программы, либо временно замените  строку
`local imageInfo = GetImageInfo(FileName);`
на
```
local imageInfo = { 
    Width = 640,
     Height = 480
}
```

**Comment by Dmitriandr** [comment]
Спасибо. Теперь работает нормально! Но буду конечно же ждать нового билда сборки. Удачи, вам!
