### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#285]
VS 2017 или 2013? 

В доке одно, по коммитам уже 17-я маячит.

**Comment by zenden2k** [comment]
По-прежнему собираю в VS 2013.
Я проверял собираемость проекта в VS 2017.
Было несколько ошибок компиляции, я их исправил.
Возникли проблемы при сборке библиотек. Оказалось, что boost подходит только определенной версии. Я выложил архивы с исходными кодами библиотек здесь, из которых я собирал.
https://drive.google.com/drive/folders/1dHjuif2sagpyNPoPs_EL63On1_A0m98N

Единственное что я не собирал, это библиотеки ffmpeg, я взял готовые библиотеки собранные в VS 2013.

**Comment by zenden2k** [comment]
К сожалению сейчас нудно быть очень терпеливым чтобы пройти весь квест по сборке библиотек.

**Comment by arhangelsoft** [comment]
Мда, попробую в 2017-й собрать, 2013-я старовата уже :( Быстро время летит.
