### ISSUE TITLE
Не работает коммандная строка

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#286]
Всё о том же #281

Условия:
Билд: 4643 с OpenSSL
В буфере есть скопированная картинка.

ситуация 1:
Программа запущена, я обращаюсь к её exe-файлу:
"<сабж>/Image Uploader.exe" /func=paste

и... никакой реакции, совсем :( 
Что-то не работает ком. строка, да и вообще коммуникация с существующим процессом. Новый процесс если и стартует, то убивается, а существующий не получает никаких инструкций.

ситуация 2:
Программа не запущена, я обращаюсь к её exe-файлу:
"<сабж>/Image Uploader.exe" /func=paste

ПО запускается в свернутом виде. Если ткнуть иконку и открыть окно, то видим стандартный диалог загрузки с картинкой из буфера. По идее он должен быть показан.

ситуация 3:
Программа не запущена, я обращаюсь к её exe-файлу:
"<сабж>/Image Uploader.exe" /func=paste /quick

ситуация 2 + ничего никуда автоматом не загружается вне зависимости от наличия картинки к буфере.

Буфер обмена - отдельный треш:
Если там ничего нет, то после вызова с /func=paste мне открывается диалог добавления без списка картинок, с кнопками возврата в гл. меню или же далее галопом по европам. Кнопка "далее" в таком случае ведет к крашу приложения. Странно что при комбинации с /quick краш не происходит, видимо имеет отношение ситуация 3-я.

**Comment by zenden2k** [comment]
Попробуйте /func=fromclipboard

**Comment by zenden2k** [comment]
@arhangelsoft 
> так и paste работает. Просто нет проверки что там есть именно картинка, или что таковая оттуда взята, по итогу я вижу диалог с кнопками, ведущими к крашу
В /func=fromclipboard есть проверка

**Comment by arhangelsoft** [comment]
> А как вы вызываете программу из браузера? Вы вроде говорили, что это невозможно.

через native messaging

**Comment by zenden2k** [comment]
В новом билде 4649 опция /quick работает совместно с /fromclipboard (или /paste)

**Comment by arhangelsoft** [comment]
> В новом билде 4649 опция /quick работает совместно с /fromclipboard (или /paste)

Спасибо, будет круто, если сможете реализовать передачу параметров существующему процессу от запускаемого.

**Comment by arhangelsoft** [comment]
Проверил. Работает.
/func=paste или fromclipboard вставляет картинку, с quick сразу её загружает.
Больше не пытается вставить непонятное содержимое буфера (файл, текст и проч.), по крайней мере я этого не вижу. Процесс схлопывается не показав ничего.

Вечером закрою запрос.

**Comment by zenden2k** [comment]
> если добавите реализацию передачи параметров существующему процессу от вновь запускаемого
Не уверен, как это грамотно можно сделать. Наверно попробую через WM_COPYDATA.
Но что делать, если уже работающий процесс сам находится в состоянии, что он не готов принимать команды? Например, уже идет загрузка на сервер. Или открыто модальное диалоговое окно, а главное окно задизэйблено.
В одном процессе у меня не предусмотрена возможность открывать несколько копий окна мастера.

**Comment by arhangelsoft** [comment]
> Но что делать, если уже работающий процесс сам находится в состоянии, что он не готов принимать команды?

Сейчас ничего, работа идёт в одну сторону без какой-либо обратной связи, т.е. так:
Chrome extension <- (JSON) -> native message -> (stdin/stdout) <- Native host app -> Image Uploader

И мой Native host app не может получить никаких данных от чем-либо от IU.

Позже Native host app может работать например как IPC клиент, и таким образом работать в обе стороны с  Image Uploader, или же вообще выполнять роль лаунчера IU если тот не запущен и далее работать по http/сокетам.

**Comment by ErikPshat** [comment]
Так пускай вновь запускаемый процесс грузит параметры в переменную, а существующий по ходу берёт данные из переменной. Либо грузить во временный файл и другим процессом считывать.

**Comment by arhangelsoft** [comment]
@ErikPshat это все костыли пока что.

P.S. Вроде работает норм, только подбешивает убивающийся процесс и остающаяся в трее иконка :(

**Comment by zenden2k** [comment]
Opera оказывается умеет сама делать скриншоты страницы
![iai4](https://user-images.githubusercontent.com/2940480/49307094-39403f00-f4e5-11e8-93e9-a1bc8dd48de5.gif)

**Comment by arhangelsoft** [comment]
хм. не знал. Мб просто потому что не пользуюсь ей...
