### ISSUE TITLE
Добавить в программу информацию о сборке

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#287]
Смотрю билд 4652, с удивлением наблюдаю что нигде нет номера сборки в самой программе.
1.3.2-beta и всё. С учетом привязки к гиту, надо бы добавить ещё и хэш последнего коммита, на базе которого собран билд.

Ну и дополнительно, разместить кнопку открывающую гит, и создающую issue со всеми важными данными, такими как OS, версия ПО, номер сборки, хеш сборки, например здесь:
![image](https://user-images.githubusercontent.com/10620040/49356854-32c8e780-f6de-11e8-8117-8d1d0e836d73.png) передать всё можно так:
гитхаб.ком/zenden2k/image-uploader/issues/new?title=<заголовок>&body=<ТЕКСТ>

на виду. Как нибудь "Сообщить об ошибке..."

**Comment by arhangelsoft** [comment]
Ха, сообщение об ошибке с отправкой сюда я нашел в "О программе".

**Comment by zenden2k** [comment]
Как нет?
![screenshot 2018-12-03 001](https://user-images.githubusercontent.com/2940480/49365389-b6430280-f6f7-11e8-88ca-52ff2053b420.png)

**Comment by arhangelsoft** [comment]
Утро понедельника, шо ты творишь со мной?)
И всё же:
?title=<заголовок>&body=<ТЕКСТ>

надо бы добавить с авто вставкой туда всего нужного.

**Comment by zenden2k** [comment]
Пока добавил только хэш коммита
![screenshot 2018-12-05 012](https://user-images.githubusercontent.com/2940480/49515838-15944480-f8a9-11e8-80aa-aedd7a42b946.png)
