### ISSUE TITLE
Не срабатывает задержка снимка

### ISSUE THREAD

**Issue by VoinNochi** [zenden2k/image-uploader#289]
Не срабатывает указанная задержка при указании снимка прямоугольной или произвольной и области и снимка элемента.
![default](https://user-images.githubusercontent.com/39955225/49509527-6dca4700-f8a7-11e8-944d-6dbe4396ab02.png)

**Comment by zenden2k** [comment]
По-моему оно всегда так работало. Так и задумано.
Ну можно попробовать исправить.

**Comment by VoinNochi** [comment]
Фишка в том, что может нужно заснять всплывающие панели или контекстные подсказки. По идее на всё про всё хватает и снимка экрана, а потом обработка редактором. Но если возможно задавать область сразу, то это пусть и 10 секунд, но экономит.

Кстати, ещё один "баг", которого нет в том же FastStone Capture - всплывающие подсказки и контекстные меню пропадают во время снимка. То есть Вашей прогой их не заснять.

**Comment by zenden2k** [comment]
Да, про этот баг я знаю.

**Comment by arhangelsoft** [comment]
@VoinNochi , @zenden2k в бете нормально снимаются как контекстные подсказки, так и контекстные меню.

**Comment by VoinNochi** [comment]
@arhangelsoft я этот баг написал после того как тут же протестировал на нескольких системных и программных контекстных подсказках. Ни одна из них не была заснята.

**Comment by zenden2k** [comment]
@arhangelsoft странно, потому что я ничего не исправлял

**Comment by zenden2k** [comment]
@arhangelsoft всё оказалось просто - был вызов SetForegroundWindow при обработке горячей клавиши

**Comment by arhangelsoft** [comment]
@zenden2k 
хм... а нельзя просто добавить опцию (хотя бы как cmd switch) чтобы разрешать возможность снимать окно UI? Да хоть скриншот-скриншота. Когда в самом IU баг или что-то показать хочется, то при снятии скриншота IU прячется.

**Comment by zenden2k** [comment]
@arhangelsoft для этого я запускаю вторую копию IU

**Comment by arhangelsoft** [comment]
@zenden2k точно
