### ISSUE TITLE
Сохранение группы изображений

### ISSUE THREAD

**Issue by VoinNochi** [zenden2k/image-uploader#290]
Обнаружил небольшой баг при сохранении группы изображений после создания коллекции картинок.
![default](https://user-images.githubusercontent.com/39955225/49567877-e2a58b80-f950-11e8-973b-d5ecc2408174.png)
При сохранении отдельных изображений окно стабильно выдаёт последнее место сохранения, тогда как при сохранении группы изображений всегда указывает стандартный диалог.
![default](https://user-images.githubusercontent.com/39955225/49568007-63648780-f951-11e8-9931-5fef151950e3.png)

**Comment by zenden2k** [comment]
Исправлено
