### ISSUE TITLE
4к разрешение

### ISSUE THREAD

**Issue by shinodem** [zenden2k/image-uploader#292]
Хотелось бы увидеть поддержку 4к, ибо сейчас при создании снимка выбранной области экран подрезается, и выделить область можно только в этой обрезанной зоне.

**Comment by zenden2k** [comment]
Буду думать, как исправить. Интересно, почему обрезается

**Comment by zenden2k** [comment]
Понятно, тогда этот баг уже известен
https://github.com/zenden2k/image-uploader/issues/191
