### ISSUE TITLE
looking to add anonfile to my server list

### ISSUE THREAD

**Issue by Zhangsun321** [zenden2k/image-uploader#293]
https://i.imgur.com/jrSYKlG.png  is the screen i get, and I do not understand russian sorry.      So if someone can direct me to how I may add https://anonfile.com/ to my choices, I would be very thankful!

Eddie

**Comment by zenden2k** [comment]
You can try this link
https://translate.google.com/translate?hl=ru&sl=ru&tl=en&u=http%3A%2F%2Fzenden2k.github.io%2Fimage-uploader%2Fru_RU%2Fadvanced.html%23servers&sandbox=1
