### ISSUE TITLE
Picasa API Deprecation

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#294]
Так как Picasa API будет отключен, необходимо переписать скрипт picasa.nut с использованием API Google Photo. 

Инфо по миграции: https://developers.google.com/picasa-web/docs/3.0/developers_guide_migration

https://developers.google.com/photos/library/guides/overview

Но всё не так уж весело: https://developers.google.com/photos/library/guides/api-limits-quotas

**Comment by zenden2k** [comment]
https://github.com/zenden2k/image-uploader/commit/80861384ae646d902f34ea77a3a30c701e822690

**Comment by mahmoudegypte** [comment]
It does not appear as an image in the editor. of WordPress Please recreate the old link
He worked with all his might
The shortcut link does not appear in the editor

![2222](https://user-images.githubusercontent.com/35723425/51357248-a4aa9400-1ac6-11e9-8100-83d5d795b2bb.png)
![1111](https://user-images.githubusercontent.com/35723425/51357249-a5432a80-1ac6-11e9-8c70-8da701539b25.png)

**Comment by zenden2k** [comment]
@mahmoudegypte 
Yeah, I know about that. Unfortunately, the new Google Photos API doesn't support direct links like Picasa API did. 
It can generate direct links, but they are only valid for 60 minutes. Such links cannot be used in forums and blogs to embed images. The link you have highlighted with red is an URL of a shared album, not of a photo. I think it makes this hosting unuseful for Image Uploader's users.
I don't know if I should keep Google Photos in the server list.

**Comment by mahmoudegypte** [comment]
I've been relying on Google Images for 7 years now and I do not know what to do. Is it possible to help me ??
I want surfer not to delete pictures at all
