### ISSUE TITLE
Why does the link look like this?

### ISSUE THREAD

**Issue by mahmoudegypte** [zenden2k/image-uploader#295]
Why does the link look like this?
![screenshot 2019-01-18 001](https://user-images.githubusercontent.com/35723425/51356923-213c7300-1ac5-11e9-8c4d-b6de17a6365f.png)

It does not appear as an image in the editor. of WordPress Please recreate the old link
He worked with all his might
The shortcut link does not appear in the editor

**Comment by mahmoudegypte** [comment]
![screenshot 2019-01-18 002](https://user-images.githubusercontent.com/35723425/51357001-84c6a080-1ac5-11e9-9053-00489b4f71a1.png)

**Comment by zenden2k** [comment]
Google Photos does not provide direct links to images.
