### ISSUE TITLE
Вылетает приложение при  нажатии "About"

### ISSUE THREAD

**Issue by EngineExt** [zenden2k/image-uploader#297]
Установлена версия 1.3.2-RC build 4713 (как узнал? Просто скачал инсталятор этот и установилось эта версия).
Нажал просмотр логов, их нет.
https://youtu.be/5sv5QGsss8Q

**Comment by zenden2k** [comment]
Подтверждаю. 
Проявляется при выборе любого языка, кроме русского и английского.
Исправлю.

**Comment by zenden2k** [comment]
Исправлено https://github.com/zenden2k/image-uploader/releases/tag/1.3.2-release
