### ISSUE TITLE
Имеется недостаток  при создании МИНИАТЮР

### ISSUE THREAD

**Issue by 52KP** [zenden2k/image-uploader#299]
При создании миниатюр, если нацело не делится, программа просто отбрасывает округление после запятой.
**_Например_**: при исходном размере фото 763 x 572 
миниатюра с заданной шириной 320 должна иметь высоту "Х".
Рассчитаем "Х"   Х=572 : 763 * 320=239,895...   
Округляем (с поправкой)   Х=240.

Т.е. правильный размер миниатюры должен быть 320 х **240**.
А реально миниатюра программой делается 320 х **_239_**.

**Comment by zenden2k** [comment]
Да, [действительно](https://github.com/zenden2k/image-uploader/blob/89457a442ed0af2d6aa5169dac96c0d2eaa4bfdb/Source/Core/Images/ImageConverterPrivate_gdiplus.cpp#L364).
