### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by smaragdus** [zenden2k/image-uploader#300]
First, I am glad that after almost 4 years a new stable version ([1.3.2 Build 4717](https://github.com/zenden2k/image-uploader/releases/tag/1.3.2-release)) has been released.

I think that '**Timeout**' does not work with '**Capture Selected Object**'- when I choose a timeout I expect the capture to be activated after the timeout is over but actually **Capture Selected Object** is activated immediately so I cannot make a proper selection to capture cascading tray menus like this:

![sshot-2019-03-31- 01-19-09](https://user-images.githubusercontent.com/9025757/55283006-29345100-5359-11e9-9af2-77d07839f901.png)

Is it possible to get a capture of this kind using **Image Uploader**? Am I missing something?

Regards

**Comment by zenden2k** [comment]
The 'Timeout' option works only with 'Capture the entire screen' and 'Capture the active window'.
It's as known bug (feature).
You can make screenshot of that kind by setting hotkey 'Capture rectangular region'
![screenshot 2019-03-31 002](https://user-images.githubusercontent.com/2940480/55285795-2d815e00-539b-11e9-9185-038bea0eb4d1.png)
It seems that 'Capture Selected Object' does not work properly with context menus.

**Comment by smaragdus** [comment]
@zenden2k 

Thank you for the immediate response and for the clarification. The workaround you suggested has one flaw- it is not as accurate as object capture. For me this is not a huge problem because I can take such screen-shots using other programs and then I can use **Image Uploader** for uploads. Anyway, native solution would be better. Have you thought of re-working the capture module? Or it would require too much time and effort? I wonder- would the code of [Free Shooter](https://github.com/henrypp/freeshooter) (C++ program) be of any help for capturing module of **Image Uploader**? I think that object capture can be improved in the future.

**Off-topic**
I am not a native English speaker but yet I think that '**Show program window**' looks and sounds better than '**Show program's window**' (see your screen-shot above).
