### ISSUE TITLE
cloud.mail.ru

### ISSUE THREAD

**Issue by Dmitriandr** [zenden2k/image-uploader#302]
Сделайте пожалуйста поддержку сайта cloud.mail.ru

**Comment by zenden2k** [comment]
Насколько я знаю, у Облака нет публичного API, поэтому могут возникнуть проблемы

**Comment by Dmitriandr** [comment]
Что ж жаль конечно. У меня на этом облаке просто папка создана, в которую я постоянно загружаю файлы вручную. А хотелось бы, чтобы ваша программа умела загружать туда файлы в определённые папки как и на фндекс-диске.

**Comment by zenden2k** [comment]
Добавил cloud.mail.ru в качестве эксперимента
Скачать тестовую версию можно здесь:
http://zenden2k.com/ru/imageuploader_nightly

Загружает по-умолчанию в папку Screenshots, но можно поменять в настройках сервера.
