### ISSUE TITLE
Не сохранются настройки в тестовой 1.3.3.4815 сборке

### ISSUE THREAD

**Issue by cannafu** [zenden2k/image-uploader#306]
Жму "применить" и ОК - окошко настроек не закрывается. Огромное спасибо за CloudMail и OneDrive - сервера работают нормально. Teknik и Pastenow тоже в порядке. Ждем финальный релиз

**Comment by zenden2k** [comment]
Наблюдается ли этот баг в сборке 4832?

http://zenden2k.com/ru/imageuploader_nightly

**Comment by cannafu** [comment]
Теперь все ОК, благодарю от души )
