### ISSUE TITLE
В последней 1.3.3.4832 сборке не отображаются сервера

### ISSUE THREAD

**Issue by cannafu** [zenden2k/image-uploader#307]
Сергей, а куда подевались сервера abload.de, lostpic.net, ge.tt, imgbb.com в настройках, в файле servers.xml вроде все раскомментировано? В 1.3.2.4717 нормально работает abload.de с авторизацией

**Comment by zenden2k** [comment]
@cannafu опечатка в XML файле

**Comment by cannafu** [comment]
Понятно, жаль, что abload.de больше не поддерживается в новой версии

**Comment by zenden2k** [comment]
исправлено
http://zenden2k.com/ru/imageuploader_nightly

**Comment by cannafu** [comment]
Спасибо, Сергей. Теперь все ОК
