### ISSUE TITLE
Сервер http://ge.tt/

### ISSUE THREAD

**Issue by cannafu** [zenden2k/image-uploader#309]
Ошибка авторизации, поправить можно, Сергей или можно забыть? На сайте заливает на ура

**Comment by zenden2k** [comment]
Какая именно ошибка?
Программа что-нибудь пишет в окне лога?

**Comment by cannafu** [comment]
Пишет
[url=https://s8.hostingkartinok.com/uploads/images/2019/07/37f2ae8ed4b8029ca3e885054b0213f5.jpg][img]https://s8.hostingkartinok.com/uploads/thumbs/2019/07/37f2ae8ed4b8029ca3e885054b0213f5.png[/img][/url]

**Comment by zenden2k** [comment]
Что там выше в логе?
Можете открыть окно лога, нажать Ctrl+A (выделить все записи), нажать Ctrl+C (скопировать в буфер) и выложить результат сюда?

**Comment by cannafu** [comment]
Вот полный лог
https://s8.hostingkartinok.com/uploads/images/2019/07/2b69869d2308e4fae13a017c10131a91.jpg

**Comment by zenden2k** [comment]
Выходит, что API сайта ge.tt позволяет загружать только в тот аккаунт, для которого получен API key (то есть мой аккаунт). Я этого не заметил, когда разрабатывал скрипт для этого сайта.
Я написал в их поддержку, посмотрим, что ответят.

**Comment by cannafu** [comment]
Понятно. Еще такой вопрос - к imgur.com никак нельзя прикрутить авторизацию?

**Comment by zenden2k** [comment]
Авторизация на imgur будет.

**Comment by cannafu** [comment]
Отлично! Благодарю
