### ISSUE TITLE
imageban error

### ISSUE THREAD

**Issue by BrevisVita** [zenden2k/image-uploader#310]
imageban.ru обновили дизайн сайта, походу что-то изменили. Кто вкурсе, проверьте пожалуйста

**Comment by zenden2k** [comment]
Вот [исправленный скрипт](https://raw.githubusercontent.com/zenden2k/image-uploader/master/Data/Scripts/imageban.nut). Проверен в Image Uploader 1.3.2 и [тестовой версии](http://zenden2k.com/ru/imageuploader_nightly). 

Я изменил только загрузку в аккаунт.
Теперь вводить пароль к сайту не требуется.
Нужно ввести ClientId и SecretKey в настройках сервера. 
![screenshot 2019-08-26 001](https://user-images.githubusercontent.com/2940480/63714612-c8973a80-c84a-11e9-82a4-d6aeb368ec5b.png)

**Comment by BrevisVita** [comment]
Спасибо, сейчас попробую изменить скрипт
