### ISSUE TITLE
imageban.ru и размер ThumbnailWidth

### ISSUE THREAD

**Issue by morefilms** [zenden2k/image-uploader#313]
Скажите, пожалуйста, как подкорректировать скрипт загрузки на imageban.ru, что бы при загрузке в свой аккаунт можно было изменить размер превью? При загрузке "как гость", т.е. не в аккаунт, его можно изменить в строке nm.addQueryParam("prew", getThumbnailWidth());
А вот при загрузке в свой аккаунт, если я верно понял, их API не позволяет принимать размер превью и льет со стандартным значением 160px. Возможно в свой аккаунт можно лить не через API в таком случае?

**Comment by zenden2k** [comment]
Да, верно, их API не позволяет принимать размер превью.
API - это предпочтительный способ общения с сервером.
Можно наверно пытаться входить под пользователем, как это делает браузер, с кукисами и т.д., но это менее надежное решение.
Я сейчас не могу вам сказать, будет ли такое решение работать с сайтом imageban или нет, потому что я не пробовал.
Для того, чтобы это сделать, надо по сути полностью переписать функцию UploadFile() в файле Data/Scripts/imageban.nut
