### ISSUE TITLE
QueryContextMenu is leaking HBITMAPs in explorer process

### ISSUE THREAD

**Issue by chrdavis** [zenden2k/image-uploader#314]
The bitmaps you pass to the menu items are getting leaked every time the menu is invoked in explorer.  Please move these HBITMAPs to class members of CIShellContextMenu, create them once in the constructor or on demand, and then call DeleteObject on them in the destructor.
Ex:

if ( ico ) {
		MenuItem.hbmpItem = Helpers::IsVistaOrLater() ? m_IconBitmapUtils.HIconToBitmapPARGB32(ico): HBMMENU_CALLBACK;
	} else {
        MenuItem.hbmpItem = Helpers::IsVistaOrLater() ? m_IconBitmapUtils.IconToBitmapPARGB32(hDllInstance, resid) : HBMMENU_CALLBACK;
	}
and

MenuItem.hbmpItem = Helpers::IsVistaOrLater() ? m_IconBitmapUtils.IconToBitmapPARGB32(hDllInstance, IDI_ICONMAIN): HBMMENU_CALLBACK;

**Comment by zenden2k** [comment]
Thank you for reporting this bug.
I will fix it when I have time.
