### ISSUE TITLE
jpegshare.net - не загружает файлы или неправильно загружает

### ISSUE THREAD

**Issue by maxvlas** [zenden2k/image-uploader#317]
На jpegshare.net не заливаются файлы

**Comment by zenden2k** [comment]
Да они перешли на https

**Comment by zenden2k** [comment]
Да они перешли на https

**Comment by maxvlas** [comment]
> Да они перешли на https

В **servers.xml** я поправил. так стоит:
`	<Server Name="jpegshare.net">
		<Actions>
			<Action Type="upload" Url="https://jpegshare.net/upload.php" PostParams="imgfile=%filename%;" RegExp="\[img\](.*?)\[([\s\S]*?)\[img\](.*?)\[" AssignVars="Thumb:0;Image:2;"/>
		</Actions>
		<Result ImageUrlTemplate="$(Image)" ThumbUrlTemplate="$(Thumb)"/>
	</Server>`
с таким выдает ошибку

В папке **Server**s лежит второй, такой **jpegshare.net 2.xml** с такой записью:
`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Servers>
    <Server Name="jpegshare.net 2">
    <Actions>
        <Action Type="upload" Url="https://jpegshare.net/upload.php" PostParams="imgfile=%filename%;">
            <RegExp Pattern="\[img\](.*?)\[([\s\S]*?)\[img\](.*?)\[" AssignVars="Thumb:0;Image:2;" />
            <RegExp Pattern='value="\[url=https:\/\/jpegshare.net\/\]\[img\](.*?)\[' AssignVars="Image:0" />
        </Action>
    </Actions>
    <Result ImageUrlTemplate="$(Image)" ThumbUrlTemplate="$(Thumb)"/>
    </Server>
</Servers>`
На нее нормально заливает

**Comment by maxvlas** [comment]
Этот фотохостинг https://jpegshare.net будет поправлен?
Не делает сейчас он превью

**Comment by zenden2k** [comment]
Dead
