### ISSUE TITLE
tinypic.com - Сайт прекратил работу. убрать из списка

### ISSUE THREAD

**Issue by maxvlas** [zenden2k/image-uploader#320]
https://tinypic.com/ прекратил работу можно убрать из списка

> TinyPic Has Ceased Operations
Due to an inability to support a high-quality free digital service that derives 100% of its revenue from ever declining on-site revenues, TinyPic has shut down its operations. As previously announced on this website, September 16, 2019 was the last day for our users to access their accounts to download their images.

What Should You Do Now?
We recommend checking out our sister company, Photobucket, for image hosting. They are currently offering an unlimited image hosting and storage plan for $5 per month (regularly priced at $11.99 per month). We would like to personally thank you for choosing TinyPic as your hosting service. Many of you have been utilizing our services since we launched back in April 2004.

**Comment by zenden2k** [comment]
Да, я уже убрал его в git-е.
