### ISSUE TITLE
Скачивание изображений с fastpic.ru

### ISSUE THREAD

**Issue by MazHaz** [zenden2k/image-uploader#330]
Image uploader не может почему-то получить изображение с фотохостинга fastpic, например с такой ссылки: https://fastpic.ru/view/114/2021/0323/_b627831773ced2157391f9811bb84892.jpg.html
 
Прямая  ссылка на изображение такая https://i114.fastpic.ru/big/2021/0323/92/_b627831773ced2157391f9811bb84892.jpg?noht=1&tk=f898&md5=HF2D7sy33Mdvp3KvehuAdw&expires=1616569200 
 
Можно ли исправить?

**Comment by zenden2k** [comment]
Программа умеет скачивать только по прямым ссылкам с любого сайта.
