### ISSUE TITLE
funkyimg.com

### ISSUE THREAD

**Issue by m1kegold** [zenden2k/image-uploader#331]
stopped working for funkyimg.com.. thanks for the fix

[11:39:48] File: C:\Users\USER\AppData\Local\Temp\tmd_iu_temp\iu_temp_a123426c\imgf6c2c5f6821633f63f2ad5d3e458e6fc.jpg
Uploading module

Upload failed! (retry limit reached)

**Comment by m1kegold** [comment]
12.01.2020 Build 4856 error code:
[img]https://funkyimg.com/i/3bD6u.jpg[/img]

**Comment by g0blin-NN** [comment]
![FunkyIMG_is_DOWN_-_2021-08-02_05 01 06](https://user-images.githubusercontent.com/66860852/127794875-03af1385-6ec8-445c-88b6-32205a112221.png)

**Comment by m1kegold** [comment]
It's very sad news.
