### ISSUE TITLE
не работает загрузка на vk.com

### ISSUE THREAD

**Issue by MazHaz** [zenden2k/image-uploader#337]
не проходит авторизация

**Comment by VeryEvilHumna** [comment]
Старые версии API ВКонтакте больше не поддерживаются. Разработчик исправил проблему, только чтобы пользоваться исправленной версией - программу нужно компилить.

**Comment by g0blin-NN** [comment]
неожиданно ночную сборку выложили
https://svistunov.dev/ru/imageuploader_nightly
