### ISSUE TITLE
Загрузка на imageban.ru

### ISSUE THREAD

**Issue by Weegley** [zenden2k/image-uploader#339]
Загрузка не работает. Неправильный адрес api.
Верный: https://api.imageban.ru/v1

LOG:

[19:43:45] Файл: FileUploadTask(D:\Temp\tmd_iu_temp\iu_temp_a1235340\screenshot 2022-03-29 002.png)
Сервер: ImageBan.ru(CScriptUploadEngine)
Модуль загрузки

imageban.nut [ThreadId=1440]
Request failed, URL: 'http://api.imageban.ru/upload_api.php'. 
Response code: 404

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by g0blin-NN** [comment]
адрес https://api.imageban.ru/v1 поменялся

**Comment by g0blin-NN** [comment]
в [этой](https://svistunov.dev/files/image-uploader-1.3.3-nightly-build-4932-openssl-portable.7z) версии все нормально.

**Comment by Weegley** [comment]
> в [этой](https://svistunov.dev/files/image-uploader-1.3.3-nightly-build-4932-openssl-portable.7z) версии все нормально.

Благодарю
