### ISSUE TITLE
на сайте не работают ссылки

### ISSUE THREAD

**Issue by g0blin-NN** [zenden2k/image-uploader#344]
например [imgupload 0.2.6](https://svistunov.dev/downloads/image-uploader-cli-win32-latest) (Win32) идет перенаправление. в [старых](https://svistunov.dev/ru/imageuploader_old_versions) тоже есть такие.

**Comment by zenden2k** [comment]
Исправил, кроме "imgupload 0.2 (OS X)", не нашёл этот файл

**Comment by g0blin-NN** [comment]
@zenden2k я клич [бросил](https://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=2420#8) на счет этого файла. не знаю есть у кого он...
