### ISSUE TITLE
Лимит загрузок исчерпан

### ISSUE THREAD

**Issue by Mrakobes666** [zenden2k/image-uploader#347]
[11:31:37] Файл: E:\Audio\Music\Metal\Post-Black Metal\Realm of Wolves\2021 - Fjordland ⁄ Nordland\Folder.jpg
Модуль загрузки

Загрузка не сервер удалась! (лимит попыток исчерпан)

---------------------
[11:32:33] Файл: FileUploadTask (E:\Audio\Music\Metal\Post-Black Metal\Realm of Wolves\2021 - Fjordland ⁄ Nordland\Folder.jpg)
Сервер: fastpic.ru (CScriptUploadEngine)
Скрипт: fastpic.nut [TID=1212]
Модуль загрузки

fastpic.nut [ThreadId=1212]
Request failed, URL: 'https://fastpic.ru/upload?api=1'. 
Failed to open/read local data from file/application

---------------

[11:32:47] Файл: E:\Audio\Music\Metal\Post-Black Metal\Realm of Wolves\2021 - Fjordland ⁄ Nordland\Folder.jpg
Модуль загрузки

Загрузка не сервер удалась! (лимит попыток исчерпан)

это новая версия программы. я зачем-то обновился((

**Comment by zenden2k** [comment]
К сожалению, новая версия не поддерживает пути к файлам, содержащие символы вне текущей кодовой страницы (` ⁄ `).
Я как-то упустил этот момент. Раньше я патчил библиотеку libcurl, чтобы она могла работать с юникодом.

**Comment by Mrakobes666** [comment]
Спасибо за ответ, я почему-то подумал про юникодные символы. Исправите?

**Comment by Mrakobes666** [comment]
кстати там еще у фастпика что то изменилось https://new.fastpic.org/

**Comment by zenden2k** [comment]
Да, можете скачать версию 1.3.3.4964 с исправлением 
https://svistunov.dev/ru/imageuploader_downloads

**Comment by Mrakobes666** [comment]
Ничего себе скорость поддержки! Респект!
