### ISSUE TITLE
Запрос на функцию отключения АВТОсохранения скриншота в файл при аплоаде

### ISSUE THREAD

**Issue by FiLinX** [zenden2k/image-uploader#348]
Собственно - вся просьба в заголовке темы)
Я по наивности, делая скриншоты и тут же только аплоадя их на разные хостинги, рассчитывал, что я никак не буду захламлять ими свои диски, но увы почему-то это не так, никакой подходящей настройки я не нашёл..
Ребята, если есть хоть какая-то возможность прекратить это автосохранение - подскажите плиз как?! 
Конечно лучше всего бы этот функционал добавить в программу)
ООООчень просим!!!!

И раз уж пишу запрос на функционал, то просьба рассмотреть и возможность захвата в скриншот - курсора мыши)
Благодарю за прекрасную программу!

**Comment by zenden2k** [comment]
Настройки -> Снимок экрана -> Папка для сохранения скриншотов (оставить поле пустым).

**Comment by zenden2k** [comment]
Скриншоты в любом случае будут временно сохраняться на диск, но будут удаляться при выходе из программы.

**Comment by FiLinX** [comment]
Ура! Оно так работает! 
Да, вижу теперь как положено в Темпе создаёт, в этой вот директории у меня  -  ...\AppData\Local\Temp\tmd_iu_temp
Спасибо @zenden2k !!  Прям сразу проблема решилась)
