### ISSUE TITLE
Управляемая .net библиотека для API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zenden2k/image-uploader#35]
```
Прошу написать библеотку для аплода 
картинок на разные хосты.

Напримеp:
using zenden.imageupload;
upimage upimage = new upimage();
upimage.file = @"pic.png";
upimage.host = @"imageshack";
upimage.send();


```

Original issue reported on code.google.com by `alim.gro...@gmail.com` on 16 Oct 2011 at 9:54

**Comment by arhangelsoft** [comment]
Чем вас Squirrel не устроил? Пиши себе, развивается по тихой грусти, уже можно многие вещи делать :) Правда одному богу известно как оно должно быть) Док-ия хромает, но  это поправимо)

Зачем эти грабли с бинарными библиотеками.

**Comment by zenden2k** [comment]
Какое отношение имеет Squirrel к данному Issue?

**Comment by arhangelsoft** [comment]
Человек хочет к лопате приделать вторую рукоять. 
т.е. удаленно управлять приложением из других языков программирования. 

Тоже самое можно и через это же приложение благодяря скриптам.

Image Uploader не компоент, а целая отдельная программа, можно конечно написать ActiveX доступный интерфейс и дергать его хоть с марса.

**Comment by zenden2k** [comment]
Если нужна "библеотку для аплода" можно просто вызывать консольную версию.
http://zenden.ws/ru/imageuploader-cli

**Comment by arhangelsoft** [comment]
Вариант) Тогда это предложение(от ТС) не имеет смысла.
