### ISSUE TITLE
add file.coffee

### ISSUE THREAD

**Issue by qzmtch** [zenden2k/image-uploader#350]
вроде как неплохой сервис [information](https://file.coffee/information) для видео в том числе, даже наверно в первую, часто стал видеть что люди кидают друг другу именно видео залитое туда, для sharex есть вот [есть поддержка](https://file.coffee/setup)

**Comment by zenden2k** [comment]
https://svistunov.dev/ru/imageuploader_nightly

**Comment by qzmtch** [comment]
ок 😉👌

**Comment by qzmtch** [comment]
> https://svistunov.dev/ru/imageuploader_nightly

а [image-uploader-1.4.0-nightly-build-4969-openssl.7z](https://svistunov.dev/files/image-uploader-1.4.0-nightly-build-4969-openssl.7z) это портабл да?

**Comment by zenden2k** [comment]
Да

**Comment by qzmtch** [comment]
всё круто, всё работает (правда пока только скриншот проверил) 👌

**Comment by qzmtch** [comment]
> Да

а ещё чтобы в других местах не спрашивать https://bintray.com/artifact/download/zenden/zenden-image-uploader/IU_Helper_0.1.1.7z этого хелпера нет нового? или старого? эта ссылка на странице с документацией лежит, а файла нет http://zenden2k.github.io/image-uploader/ru_RU/advanced.html

**Comment by zenden2k** [comment]
https://svistunov.dev/files/IU_Helper_0.1.1.7z
Только он уже почти не работает (в нем не открываются https сайты).
Я не планирую его развивать.

**Comment by qzmtch** [comment]
> https://svistunov.dev/files/IU_Helper_0.1.1.7z Только он уже почти не работает (в нем не открываются https сайты). Я не планирую его развивать.

ок спасибо, я просто потестить 😉
