### ISSUE TITLE
Build 5117 - в миниатюрах не выбирается вид transp

### ISSUE THREAD

**Issue by forapreder** [zenden2k/image-uploader#357]
Windows 10 Pro 22H2 сборка 19045.3086 x64

В портабельном билде 5117 x64 в миниатюрах при выставлении в настройках вид transp и любой другой - фактически не применяется, Все миниатюры показываются прямоугольниками без рамки.
Причем надписи параметров загруженной картинки скачут то вверху, то внизу картинки: на fastpic.ru - внизу, на imageban.ru - вверху.
В портабельном билде 4971 x64 все нормально.
![1001](https://github.com/zenden2k/image-uploader/assets/60479869/0a0f082e-2427-4880-b8f2-5d698ee07789)

**Comment by zenden2k** [comment]
Такие миниатюры бывают при включенной опции "Использовать серверные миниатюры"
