### ISSUE TITLE
Clarification by adding ftp/sftp server

### ISSUE THREAD

**Issue by hossamea** [zenden2k/image-uploader#361]
Hello

 

I use Image Uploader heavily and it is useful and there is no problem, but I try to use add ftp/sftp server

And that on my server, but I fail to put the correct data.

If there is a detailed explanation of adding the server and putting the correct data, I will be grateful to you

**Comment by zenden2k** [comment]
Unfortunately SFTP is not working in Image Uploader v1.3.3.4964 (my mistake).

When adding a FTP server, there are fields:
- server (here goes server's domain name, for ex. "example.com")
- login
- password
- remote directory (root directory of your ftp server, usually "/")
- URL for downloading- first part of public URL where file can be downloaded (will be joined with file name), for ex. "https://example.com/download/"

SFTP server support is available in Build 5118 (2023-07-02).
The fields are practically the same but you may need to specify the private key file (<user>\.ssh\id_rsa )

**Comment by hossamea** [comment]
Thank you, the FTP server has been successfully completed.

Is it possible to download link Build 5118?

**Comment by zenden2k** [comment]
https://svistunov.dev/ru/imageuploader_nightly
