### ISSUE TITLE
Добавить поддержку postimages

### ISSUE THREAD

**Issue by m1kegold** [zenden2k/image-uploader#363]
Спасибо за отличную программу! Очень давно пользуюсь.

Можно ли добавить поддержку https://postimages.org/

Спасибо.

**Comment by zenden2k** [comment]
Хостинг postimages.org давно доступен в ночных сборках. Когда выпущу релиз, не знаю.
Я сейчас попробовал загрузить. Не работает загрузка как на самом сайте, так и в Image Uploader.
ERR_CONNECTION_TIMED_OUT

**Comment by qzmtch** [comment]
> Хостинг postimages.org давно доступен в ночных сборках. Когда выпущу релиз, не знаю. Я сейчас попробовал загрузить. Не работает загрузка как на самом сайте, так и в Image Uploader. ERR_CONNECTION_TIMED_OUT

только что попробовал, и сайт работает нормально, и с image uploader загрузил нормально https://i.postimg.cc/Xvtk1fgX/screenshot-2023-12-29-001.png

**Comment by m1kegold** [comment]
>>> Хостинг postimages.org давно доступен в ночных сборках.

Спасибо за наводку. Скачал, установил, всё грузит. Была, наверное, какая-то проблема временная у них.
