### ISSUE TITLE
Добавить поддержку userscloud

### ISSUE THREAD

**Issue by qzmtch** [zenden2k/image-uploader#364]
https://userscloud.com/  на главной до 5 GB написано, но в факе Unlimited file size. 
вроде норм сервис, видео позволяет смотреть прямо с их интерфейса, для этого его и можно использовать https://userscloud.com/enfe56wae1c9 только webm не определяет как видео, видимо только mp4

и https://staging.streamable.com/ тоже можно было бы добавить, он вроде был заблокирован в рф, но сейчас вот работает. То ли сняли, то ли сайт с припиской staging. не заблочен, хз, работает в общем и довольно популярный для как раз хостинга видео

**Comment by zenden2k** [comment]
> https://userscloud.com/
Страница авторизации не пускает меня. Защищена Cloudflare.
Ну, значит будет только анонимная загрузка.

> https://staging.streamable.com/

В документации к API отсутствует возможность загрузки файлов.
Загрузка через браузер, похоже, как-то сложнее устроена. Лень копаться в обфусцированных скриптах.

**Comment by qzmtch** [comment]
> В документации к API отсутствует возможность загрузки файлов.
> Загрузка через браузер, похоже, как-то сложнее устроена. Лень копаться в обфусцированных скриптах.

ок, первый хотя бы, этот второй по сути только для видео сделан, да и скачивать не даёт (если не лезть в network за ссылкой), только для посмотреть
