### ISSUE TITLE
Проблема при использовании горячих клавиш.

### ISSUE THREAD

**Issue by Mogikan7** [zenden2k/image-uploader#365]
Здравствуте!
Возникает ошибка при активации "Снимок последней области" (не понятно что это вообще такое) горячими клавишами.
![область](https://github.com/zenden2k/image-uploader/assets/156675379/0d03f909-aeac-49bf-9c9a-88631a45bc1d)
![область2](https://github.com/zenden2k/image-uploader/assets/156675379/2d4871df-f175-407b-8c56-3de028f61ad3)

Надеюсь, что на скринах всё понятно.
Спасибо!

**Comment by zenden2k** [comment]
Предполагается, что до этого вы уже выбирали какую-то область экрана и делали скриншот.
Эта функция позволяет повторить скриншот той же области.

**Comment by Mogikan7** [comment]
Ааааа....
А тогда получается, что сделать "снимок выделенной области" используя ГК невозможно?
А было бы неплохо!
Спасибо за отличную программу!

**Comment by zenden2k** [comment]
снимок выделенной области = снимок прямоугольной области

**Comment by Mogikan7** [comment]
Спасибо за подсказку - не додумался проверить, верил написанному :))
