### ISSUE TITLE
[Feature request] Adjustable blurring level

### ISSUE THREAD

**Issue by Alex-302** [zenden2k/image-uploader#369]
Привет

Иногда нужно выделить определённую область, но так, чтобы остальное содержимое можно было прочесть или понять что к чему (в инструкции, например, как дополнение к указанию стрелками или без них). Сейчас это стало возможным благодаря инверсному режиму (спасибо за эту функцию:) ) Но степень размытия фиксированная и довольно высокая - работает как маскировка.

![image](https://github.com/zenden2k/image-uploader/assets/8361299/1d7ebc97-00a5-49d9-9246-c9d928b6859e)

У KISS есть настройка степени размытия и можно сфокусировать внимание на определённой области не делая остальное содержимое нечитаемым

![image](https://github.com/zenden2k/image-uploader/assets/8361299/bd49dea0-40ef-4fd3-a5ec-107858b3db07)
![image](https://github.com/zenden2k/image-uploader/assets/8361299/7a7003f2-ebd4-4936-9c9a-03399b258ef8)

**Comment by zenden2k** [comment]
Будет.

**Comment by Alex-302** [comment]
Проверил в найтли - то что надо. Спасибо!
