### ISSUE TITLE
imgur удаляет ссылки .png

### ISSUE THREAD

**Issue by qzmtch** [zenden2k/image-uploader#371]
С недавних пор, часто стал замечать после загрузки, что по моим ссылкам 404 вместо скриншотов.
Решил проверить скрины не по прямой ссылке, и они были доступны, открыл в новой вкладке, а там .webp
и по прямым только webp, png после заливки удаляются, а в imageuploader .png приходят в ответ же
Надо как то или менять на webp если приходят так или ещё как то фиксить это (если это не только моя проблема)

PS но не всегда удаляет, а как то выборочно, иногда остаются

**Comment by zenden2k** [comment]
Я так понимаю, что удаляет те, что загружены без аккаунта?

**Comment by qzmtch** [comment]
> Я так понимаю, что удаляет те, что загружены без аккаунта?

ну я без аккаунта пользуюсь да, может и с аккаунтом тоже
там такая странность, сейчас потестил, может это косяк имгура
вот загрузил скриншот https://i.imgur.com/8bhouPX.png и если открыть его так https://imgur.com/8bhouPX то он есть но не открывается в новой вкладке изображение, и кликом по картинке не увеличивается https://i.imgur.com/Lpj0lHN.png (ну и вот опять сделал скрин и он так вот не загружается, а так доступен, но без увеличения https://imgur.com/Lpj0lHN ) пишет что не может загрузить
вот так она доступна https://i.imgur.com/8bhouPX_d.webp?maxwidth=760&fidelity=grand
но если убрать размер и _d в конце то вот так https://i.imgur.com/GnhN57N.png
ладно, если это не косяк апи, то косяк имгура наверно
