### ISSUE TITLE
Копирование в буфер BBcode для форума

### ISSUE THREAD

**Issue by sm677** [zenden2k/image-uploader#374]
Приветствую. Подскажите пожалуйста, можно ли, чтобы после загрузки изображения, автоматически, вместо URL ссылки в буфер копировались BBcode для форума (Эскизы с увеличением по клику) ?
Спасибо.

**Comment by zenden2k** [comment]
Программа запоминает выбранные настройки в окне с результатами.
Эскизы с увеличением по клику будут выбраны по-умолчанию, если перед загрузкой была включена опция "Создавать миниатюры (превью)"

**Comment by sm677** [comment]
использую горячую клавишу, заливается картинка, и в буфер автоматически копируется прямая ссылка, даже если выставлены настройки BBcode для форума (Эскизы с увеличением по клику)

Сделайте пожалуйста, чтоб в буфер после загрузки (автоматически) копировалась ссылка, которую включаешь, например BBcode для форума.
Спасибо

**Comment by zenden2k** [comment]
Доступно в ночной сборке
https://svistunov.dev/ru/imageuploader_nightly

![screenshot 2024-08-04 17-08-41 001](https://github.com/user-attachments/assets/43655892-7b9d-4770-ae66-ba1cdcbfab8d)
