### ISSUE TITLE
5191: the index 'getFileName' does not exist

### ISSUE THREAD

**Issue by DPlFnAz5J91kerf** [zenden2k/image-uploader#381]
Беру пример фильтра из uploadfilter_8h.html и пробую залить картинку:
```
[13:28:29] 
Script.cpp:151

example.nut [ThreadId=14196]

AN ERROR HAS OCCURED [the index 'getFileName' does not exist]

CALLSTACK
*FUNCTION [PreUpload()] example.nut line [4]

LOCALS
[reserved] 0
[task] INSTANCE
[this] TABLE
```

В 5186 работает.

**Comment by zenden2k** [comment]
Спасибо, что сообщили. Исправлю.

**Comment by zenden2k** [comment]
Внёс некоторые изменения в API. Теперь в функцию PreUpload и PostUpload передается объект типа UploadTaskUnion, из которого можно получить задачу нужного типа.

https://zenden2k.github.io/image-uploader/api/html/uploadfilter_8h.html#UploadFilters
