### ISSUE TITLE
Пробелы в имени файла при выгрузке на FTP

### ISSUE THREAD

**Issue by BlagoYar** [zenden2k/image-uploader#386]
При выгрузке по FTP файла с пробелами в имени, получаю вместо них подчёркивание.
Можно или убрать такое поведение или сделать возможность их убирать?

**Comment by zenden2k** [comment]
Сделаю

**Comment by BlagoYar** [comment]
Спасибо! А то уже второй день мучаюсь, думал это либо nginx/vsftpd. Оказалось IU.

**Comment by BlagoYar** [comment]
> Сделаю

Спасибо ещё раз! Есть нюанс "проблемными" названиями, например такой файл
`Терминал Linux #3 - Команда Grep_ поиск по файлам и папкам.mp4`

Закачивается как 
`Терминал Linux `

То есть имя до решётки.

**Comment by zenden2k** [comment]
Да, стоит применить процентное кодирование имени файла.

**Comment by zenden2k** [comment]
Сделаю просто, если файл существует, то добавляю 6 случайных символов в конец
