### ISSUE TITLE
сделать возможность заливки картинок\файлов на http://joxi.ru

### ISSUE THREAD

**Issue by GoogleCodeExporter** [zenden2k/image-uploader#65]
```
сделать возможность заливки 
картинок\файлов на http://joxi.ru. 
```

Original issue reported on code.google.com by `zenden2k` on 9 Mar 2015 at 12:14

**Comment by arhangelsoft** [comment]
Не реализуемо в настоящее время. Сервис не предоставляет API для сторонних разработчиков. Ни до ни после авторизации, так же нет веб-форм загрузки изображений.

**Comment by zenden2k** [comment]
незачем рекламировать проект конкурентов
