### ISSUE TITLE
не работает клавиша.

### ISSUE THREAD

**Issue by Fedosyk** [zenden2k/image-uploader#67]
Добрый вечер. Хочу назначить горячую клавишу, нажимаю print scrin а вместо этого unknoun. Как это исправить? win8.1 64bit
Клавиша del то же unknoun

**Comment by zenden2k** [comment]
Не получается воспроизвести.
Если у вас не нажимается клавиша, вы можете  нажать правой кнопкой мыши по полю, и выбрать нужную клавишу в меню. В новой версии в меню добавлен PrintScreen.
http://zenden.ws/ru/imageuploader_downloads

**Comment by zenden2k** [comment]
>Не могу понять, в горячих клавишах нажимаю принт-скрин, дел, хоме а они не срабатываю, пишет ункноу. Может можно исправить? Готов помогать логами и т.д. 
И ещё, не может эта программа влиять на специальные возможности-залипание клавиш, у меня почему то клавиша win перестала залипать? О, только обнаружил, клавиши не определяются если skype запустить. Если выйти из скайпа то и win работает и в Вшей программе всё путём.
