### ISSUE TITLE
Alternative Application Icon

### ISSUE THREAD

**Issue by thrylmz** [zenden2k/image-uploader#73]
I have designed the application icon for Image Uploader.
:white_check_mark:Optionally, can be used by Everyone 

:free:**The icons are in the folder**

![icon_app1](https://cloud.githubusercontent.com/assets/3826313/6705679/01f0c16a-cd60-11e4-9f5c-a2e302ab1fd6.png)

https://drive.google.com/folderview?id=0B_19jCHngtp4fnRqV0YtbE1rVHBvcXhDWjhiRDR3eVRFc1FSYzFuNjNsZC1feWl5ZTJHZVU&usp=sharing

![icon_app2](https://cloud.githubusercontent.com/assets/3826313/6705680/03aa6f9c-cd60-11e4-9fac-6d1264bd1053.png)

https://drive.google.com/folderview?id=0B_19jCHngtp4fmJndnZjU3FOUXpId001Q1VpY1lxSEpxMm0ySVRmcXl5cm9uRFRBcm03bXM&usp=sharing

**Comment by zenden2k** [comment]
Good job, but can you make a few changes, or give me Photoshop/Illistrator file so i can make it on my own.
![changes](http://fs1.directupload.net/images/150318/9hbeodf7.png)

**Comment by thrylmz** [comment]
PSD File: https://drive.google.com/file/d/0B_19jCHngtp4QkZIOWdLYlNHT2c/view?usp=sharing

**Comment by thrylmz** [comment]
I added the 3 style package if you want to use
https://drive.google.com/file/d/0B_19jCHngtp4bFBaNTNqVXppR28/view?usp=sharing

**Comment by zenden2k** [comment]
Added in the latest build http://zenden.ws/imageuploader_downloads
