### ISSUE TITLE
Ограничение поддерживаемых файлов хостингом а так же Squirrel::GetFileMimeType

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#74]
Собственно хостинги ограничиваются не только рамером файла, но и весьма успешно типами файлов.
Что если это тоже учитывать, на уровне программы?
т.е. если изображений хостинг чуть менее чем рандомный, то ПО таким образом ищет тот, который поддерживает расширение файла и отправляет туда.

т.е. некий скрипт/xml атрибут задает список поддерживаемых файлов по расширению, т.е. так "png;jpg" для одного хостинга и для другого "gif;png;jpg;xps"

в squirrel запилить какую-нибудь GetSupportedExtenstionlist() {
 local a = ["png","bmp","etc..."];
}

эту проверку можно и в скрипте написать, но проблема в том, что IU не сможет сделать 2 крутые вещи:
1. Для выбранного списка файла предложить те сервера, которые их поддерживают.
2. При лучайном выборе хостинга, nut не может сказать "передай другому, я не умею это", и цепочка обломится с ошибкой.
3. Хостинг не поддерживает, юзер это не знает, грузит картинку и ложит непонятные предметы "Почему не работает?!111"

Собственно в servers.xml завести атрибут exts="" для type="image", в котором перечисляются через запятую, расширения, которые поддерживает конкретный хостинг картинок.

По расширения файла выдавать на выбор естественно те хостинги, которые поддерживают указанный формат.

Аргументирование: Image Uploader ну вот совсем никак не помог мне загрузить gif на хостинг. Вся прелесть в том что, все фото-хосты поддерживают gif вот таким образом: вырезают первый фрейм и считают, что успешно загрузили картинку.

**Comment by zenden2k** [comment]
Идея загрузки на случайный сервер мне не нравится. Такая функция не поддерживается, хотя может она и работает (когда-то работала). Можно просто перед загрузкой проверить список файлов (по списку поддерживаемых расширений) и предложить юзеру выбрать другой сервер.

>GetFileMimeType() отсутсвует в бинарной версии IU, на данный момент. Скрипт не собрался с вызовом этой функции. 

Да ладно ? ![img](http://fs1.directupload.net/images/150318/v2o6wk3m.png)

**Comment by arhangelsoft** [comment]
а не, она действительно есть, но не работает с иминем файла. Путь к файлу действительно как-то влияет на тип?
	local name = ExtractFileName(FileName);
	local mime = GetFileMimeType(name);
	DebugMessage(mime); //Пусто :)

**Comment by zenden2k** [comment]
Да, влияет. Она проверяет по содержимому, а не по расширению. См. [FindMimeFromData](https://msdn.microsoft.com/en-us/library/ie/ms775107(v=vs.85).aspx).
А на unix используется команда ```file -b --mime-type```

**Comment by arhangelsoft** [comment]
будем-с знать, спасиб за функцию, полезно)

**Comment by arhangelsoft** [comment]
Оно как feature, актуально?

**Comment by zenden2k** [comment]
@arhangelsoft 
актуально

**Comment by zenden2k** [comment]
Реализовано.
