### ISSUE TITLE
Squirrel::дублирование исключений в логе

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#76]
Доброго, собсвенно сабж:
![19 03 2015 12 10 003](https://cloud.githubusercontent.com/assets/10620040/6727220/124401ae-ce31-11e4-8f50-176c908cb229.png)

Первая строка несет всю полезную информацию, вторая уже не имеет смысла и занимает место, 3я - констатация факта.

**Comment by zenden2k** [comment]
Да ладно вам, эта информация видна только при ошибке во время разработки, вторая запись это обработанное исключение, исключение может сгенериться по какой-то другой причине (не только ошибка компиляции).
