### ISSUE TITLE
Проблема с миниатюрами (1.3.1 alpha build 4229)

### ISSUE THREAD

**Issue by maxvlas** [zenden2k/image-uploader#78]
Скачал следующее:
Image Uploader 1.3.1 alpha build 4229 Installer
Image Uploader 1.3.1 alpha build 4229 portable
**********************
Что то эта версия проблемная,не хочет превью грузить (галка стоит в настройках)
Пробовал разные фотохостинги,выдает ошибку
http://fs2.directupload.net/images/150320/l7ia8bre.png

была такая проблема с добавлением фотохостинга http://www.bild.me/
http://forum.ru-board.com/topic.cgi?forum=5&topic=27858&start=920#20 Здесь просил исправить :smile: с данным фотохостингом http://www.bild.me/ (чтоб не ставить галку "Использовать серверные миниатюры")

теперь наоборот все стало, на все фотохостинги надо ставить галку  "Использовать серверные миниатюры" :smile:, в итоге Получается что превью захочешь не настроишь
------------
1.так не грузит миниатюры - ошибка
http://fs1.directupload.net/images/150320/ck9hfk59.png

2.так не грузит миниатюры - ошибка
http://fs1.directupload.net/images/150320/avrps88f.png

3.так только грузит миниатюры - нормально
http://fs2.directupload.net/images/150320/c5p7twwu.png

**Comment by zenden2k** [comment]
fixed
