### ISSUE TITLE
Squirrel::regexp.match не корректно работает, и модификации regexp

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#79]
Доброго времени, собстенно есть строка:<br/>
`<input name="authenticity_token" type="hidden" value="jFhcGv/9a/agJqoSmzsCsmw13zV0ueGobbBUfMKMNGI=" />`

Вот регулярка для поиска необходимого, допустим атрибут **name** должен быть 
**authenticity_token**:<br/>
`name=['"]authenticity_token['"]`

использую так:
`local re = regexp(format("%s=['\x22]%s['\x22]","name","authenticity_token"));

if(re.match("<input name="authenticity_token" type="hidden" value="jFhcGv/9a/agJqoSmzsCsmw13zV0ueGobbBUfMKMNGI=" />")) 
DebugMessage('ok')
 else 
DebugMesage("fail")`

Просто обязано вернуть мне `ok`, [согласно](https://regex101.com/r/yR4aS7/1) http://regex101.com совпадение есть.

метод класса же вернет false.

Второе, не нашел включения различных модификаторов, в частности для данного regexp есть разница между CAT и CaT и cat и Cat это 4 разных слова. 

Что очень и очень плохо :)

Можете реализовать свой класс на основе PCRE библиотеки?

**Comment by zenden2k** [comment]
Да в squirrel какой-то урезанный движок регулярных выражений

**Comment by zenden2k** [comment]
```javascript
	local reg = format("%s=['\x22]%s['\x22]","name","authenticity_token");
	local re = regexp(reg);
	local str = "name=\"authenticity_token\'";
	WriteLog("error",reg);
	WriteLog("error",str);
	if(re.match(str)) 
	WriteLog("error","ok");
	else 
	WriteLog("error","fail");
```
печатает ok

**Comment by arhangelsoft** [comment]
хм.. собственно вот что я пишу:
function log(msg) {
    print(msg+"\n");
}

/*
    Squirell::common functions
   
    name: HTML_getAttributeValue
    Description:
        Parses HTML text and extract some atribute value from specified node.
   
    Input parametrs:
        html - HTML source code, in any case.
        tagname - name of the HTML tag, e.g. input, ul, li, etc
        selname - selector attribute name, e.g. id, name, can be class if it have one value
        selvalue - value of the selector to find a true node from the scope
        resultattr - the same as selname, for extracting it value for return.
       
   
*/
function HTML_getAttributeValue(html, tagname, selname,selvalue, resultattr) {
    local sRe_node_search = "<%s(.+)[\\/]>"; //Search all node with specified tagname value CASE SENSETIVE
    local sRe_attr_search = "%s=['\x22]%s['\x22]"; //Search aattributes with specified selname value CASE SENSETIVE
    local sRe_attr_value_search = "%s=['\x22](.+)['\x22]"; //Search aattribute with specified resultattr value CASE SENSETIVE
   
    local ret = "";
    local re_nodes = regexp(format(sRe_node_search,tagname));
    local aNodes = re_nodes.capture(html,0); //array if tables
    local i_nodes = 0;
    local tNode;
    if(aNodes != null) {
        log("aNodes not null");
        foreach(i_nodes,tNode in aNodes) {
            local sNode = html.slice(tNode.begin, tNode.end);
            log(format("[%d] %s",i_nodes,sNode));
            local re_attr = regexp(format(sRe_attr_search,selname,selvalue));
            //regexp.match not working propertly
            /*
                string: <input name="utf8" type="hidden" value="&#x2713;" />
                pattern: name=['"]utf8['"]
               
                regex101.com returns valid result, that's pattern is matched with string.
                regexp.match returns always false.
            */
            local re_attrmatches = re_attr.search(sNode,0);
           
            if(re_attrmatches != null) {
                log("re_attrmatches == true");
                local re_result = regexp(format(sRe_attr_value_search,resultattr));
                local re_result_a = re_result.capture(sNode, 0);
                if(re_result_a != null) {
                    ret = sNode.slice(re_result_a[1].begin, re_result_a[1].end);
                    log("ret = "+ret);
                    break;
                }
            } else log("match == false");
        }
    } else log("nodes = null");
   
    return ret;
}

function  UploadFile(FileName, options)
{       
    nm.setUrl("http://imgbox.com/login");
    nm.doGet("");
    if(nm.responseCode() == 200) {
        local sHTML = nm.responseBody();
        HTML_getAttributeValue(sHTML,"input","name","utf8","value");
        return 1;
    } else {
        return 0;
    }   
   
}

Приходится использовать `re_attr.search(sNode,0);`
и дальнейший гемор с проверкой != null, хотя тут match ф-ия очень даже к месту.

Далее, очень и очень хотелосьбы чтобы движок поддерживал модификаторы, типа i g f и т.д. пока что данная утилита исправно выгребает  необходимое из HTML кода, но чувствительна к регистру, от чего хотелось бы избавится.

**Comment by arhangelsoft** [comment]
адовый редактор сообщений github :-[

**Comment by zenden2k** [comment]
Когда будет время, запилю функции-аналоги php  preg_match и preg_match_all, на основе pcre и с поддержкой модификаторов

**Comment by zenden2k** [comment]
А вообще у меня была идея приделать парсинг HTML с помощью этой либы
https://github.com/google/gumbo-parser
А еще написать на его основе библиотеку CppQuery (аналог jQuery, phpQuery для C++). Но это так, мечты.

**Comment by arhangelsoft** [comment]
Можно конечно, но это долго и геморойно, а вот прикрутить мощь XPATH куда проще к XML, тем более что tinyxml его поддерживает [ввиде доп. либы](http://tinyxpath.sourceforge.net/). Преобразование HTML в XML можно сделать с помощью Tidy либы: http://tidy.sourceforge.net/libintro.html

тогда будет классно и для HTML и для XML. Однако парсеры типа моей ф-ии писать придется, если что-то затесалось в блок JS.

**Comment by arhangelsoft** [comment]
>Когда будет время, запилю функции-аналоги php preg_match и preg_match_all, на основе pcre и >с поддержкой модификаторов

Лучше класс со свойствами и методами, как в случае с сетевым менеджером.

**Comment by arhangelsoft** [comment]
Алсо есть целая либа на замену TinyXML которая умеет парсить HTML: http://htmlcxx.sourceforge.net/ но что-то подсказывает просто залезть в TinyXML + TinyXPath

**Comment by zenden2k** [comment]
Ну можно и класс и функции, просто при использовании функций код получится короче.
Эх как хорошо, что я в своё время выбрал Squirrel, а не более популярный Squirrel. Просто мне был ближе синтаксис C. Вам наверное ближе синтаксис Lua, он похож на Delphi. Недавно узнал, что Squirrel использовался в  игре Left 4 Dead 2, да и много где еще.

**Comment by zenden2k** [comment]
Да этих либ куча, другое дело, к какой будет проще написать обертки,
библиотека для биндинга с++ к squirrel какая-то недоделанная, ей нужно подавать функции в особом виде. Или я плохо её понимаю. Документация конечно же скупая, вернее её вообще нет.

**Comment by arhangelsoft** [comment]
На Squirrel писать довольно легко. По крайней мере мне, однако скудоват он в стандартном пакете. Очень очень. 

>Да этих либ куча, другое дело, к какой будет проще написать обертки,
TinyXML + TinyXPath это просто заголовочный включить, далее в Simple Xml дописать функцию, которая вернет таблицу узлов XMLNode по совпадению XPath. 
Для Squirel написать функцию, HTMLtoXML(string) на выходе экземпляр Simple xml с рутовым узлом html.

Вроде все.

**Comment by zenden2k** [comment]
Создал сам себе issue https://github.com/zenden2k/image-uploader/issues/80

**Comment by arhangelsoft** [comment]
случаем не вкурсе как в скрипт сквиррела линковать модули? приходится копипастить всякие функции из других модулей, а если в них что-то править - караул...

**Comment by arhangelsoft** [comment]
В скриптах L4D2 точно такое есть, не помню как...

**Comment by zenden2k** [comment]
See the Squirrel docs for dofile() and loadfile().

**Comment by arhangelsoft** [comment]
попробуем-с

**Comment by zenden2k** [comment]
Тут такой вещью занялся, из спортивного интереса, есть такой скриншотер joxi.ru
Ну я заснифал его HTTPS трафик, сделал скрипт 
```
function  UploadFile(FileName, options)
{
	nm.setUrl("https://api.joxi.net/drive/v1/files?fields=id,alternateLink,selfLink");
	nm.addQueryHeader("Content-Type", "application/json");
	nm.addQueryHeader("User-agent", "");
	nm.addQueryHeader("Authorization","Bearer " + token);
	nm.setCurlOptionInt(213, 1); // CURLOPT_TCP_KEEPALIVE
	nm.addQueryHeader("Accept-Language", "ru-RU,en,*");
	
	local description = ExtractFileName(FileName);
	try {
		description = ExtractFileNameNoExt(FileName);
	} catch ( ex ) {
		
	}
	local postData = {
		description = description,
		mimeType = "image/vnd.joxi.screenshot"
	};
	nm.doPost(ToJSON(postData));
	DebugMessage(nm.responseBody());
	return 0;
	if ( nm.responseCode() == 201 ) {
		local t = ParseJSON(nm.responseBody());
		local link = t.alternateLink;
		local uploadUrl = str_replace(t.selfLink,"http://", "https://") + "?fields=id";
		nm.addQueryHeader("User-agent", "");

		nm.addQueryHeader("Authorization","Bearer " + token);
		nm.addQueryHeader("Content-Disposition","attachment; filename*=UTF-8'ru'" + name + "." + GetFileExtension(FileName));
		nm.addQueryHeader("Accept-Language", "ru-RU,en,*");
		nm.setUrl(uploadUrl);
		nm.setMethod("PUT");
		nm.doUpload(FileName, "");
		if ( nm.responseCode() == 200 ) {
			DebugMessage(nm.responseBody());
			local json =  ParseJSON(nm.responseBody());
			nm.addQueryHeader("User-agent", "");
			nm.setUserAgent("t");
			nm.addQueryHeader("Authorization","Bearer " + token);
			nm.addQueryHeader("Accept-Language", "ru-RU,en,*");
			nm.doGet("https://api.joxi.net/drive/v1/about");
			DebugMessage(nm.responseBody());
			
			
			options.setDirectUrl("http:"+json.downloadUrl);
			options.setViewUrl(json.alternateLink);
			options.setThumbUrl("http:"+json.thumbnailLink);
			return 1;
		}
		return 0;
	}
		
	return 1;
}
```
он вроде и заливает, но ссылки выходят нерабочие. Особенность этого скрипта в том, что значение User-agent это пробел " ". Оказалось, что CURL игнорирует заголовки, значения которых состоят из одних пробелов. Вот это прикол.

**Comment by arhangelsoft** [comment]
о_О копал под него, но не нашел ни API ни веб-форм... расширение под хром раздербанили?

**Comment by zenden2k** [comment]
О, хорошо что вспомнили про расширение, посмотрю, как сделано там. Но чую, что там опять чертов пробел.
Поскольку все мои снифалки обломались с joxi, а прокси Fiddler-a он игнорировал, пересобрал библиотеку Qt5Network.dll, добавив  в класс QSslSocket логгинг в файл (благо на моем Core i7 все это компилилось минут 5).

**Comment by arhangelsoft** [comment]
На  будущее, купите себе маршрутизатор, лучше программируемый MikroTik. Поимеет любую VPN-сеть, прокси-сервер и прочее, простым перебросом портов назад на машину через прокси того же Fiddlera.

**Comment by arhangelsoft** [comment]
Закрытое API я бы даже не трогал. Это опа, т.к. его меняют как хотят и когда захотят. Когда будет публичный, был бы смысл заниматься этим.

**Comment by zenden2k** [comment]
Зря я не вспомнил про экстеншн. Там всё как на ладони. 
Их клиент умеет самообновляться? Если нет, тогда api они не будут менять

**Comment by zenden2k** [comment]
Да я просто из спортивного интереса, еще не было хостинга, который бы мне не поддался,
Я думал прикрутить еще mega.co.nz но там какой-то огромный SDK на C++ с зависимостью, я думал отделаться squirrel скриптом.

**Comment by arhangelsoft** [comment]
>А вот токены экстеншена мне кажется они могут менять хоть каждый день
как пропалят что токены не от хрома )) 

>Их клиент умеет самообновляться? Если нет, тогда api они не будут менять.

Не обновляющееся приложение это мертвое приложение :) Ну не автоматом, так "A new version avaliable. Please go to the offical web site and download it"

**Comment by arhangelsoft** [comment]
mega.co.nz облачный файл-хост в виде флешки. Суровые парни. Скриптом не отделаться, как минимум динамическая либа-плагин.

**Comment by zenden2k** [comment]
Какой флешки? там всё на HTML5. Если бы раскопать API, а не SDK, можно отделаться скриптом + функция шифрования на С++

**Comment by zenden2k** [comment]
Надо бы еще google drive прикрутить

**Comment by zenden2k** [comment]
В Image Uploader содержится весь OpenSSL, там какие угодно функции шифрования, тянуть ради одного хостинга целый sdk как-то не хочется

**Comment by arhangelsoft** [comment]
C API вряд ли разобраться получится, там что на AJAX. Да ещё JS приходит закодированный и т.д. и т.п. кароче SDK лучше.

**Comment by arhangelsoft** [comment]
OpenSSL это понятно. Вещъ. Однако SDK это какой-то мало изменяемый стандарт позволяющий написать свой вынъ клиент в облако. 

По хорошему надо бы грамотно придумать что-то для хостов где есть деревья папок.

**Comment by zenden2k** [comment]
Что имеете ввиду? Чтобы можно было раскрывать и смотреть подпапки?

**Comment by arhangelsoft** [comment]
да, ну и более-менее понятные доки по скриптам генерации дерева папок.

**Comment by zenden2k** [comment]
Ну по-хорошему надо сделать динамическую подгрузку подпапок. Сейчас подпапки могут отображаться, но для этого надо запросить с сервера ВСЮ структуру, что конечно же, не есть гуд.

**Comment by zenden2k** [comment]
Вот набросал доки
http://rawgit.com/zenden2k/image-uploader/master/Docs/api_regexp.html
сам класс еще не готов
