### ISSUE TITLE
Squirrel::Локализация

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#81]
Как-то уже писал по этому поводу.

Начиная с 1.3 мы имеем парсер XML в скриптах.

Собственно задумка такая: 
В папку lang кинуть файл scriptstrings.xml какой-нибудь,
Который содержит такую структуру:
`<locales>
  <script name="hostcom" default="en">
      <language locale="en" name="English">
          <locale match="язык оригинала" />
      </language>
      <language locale="ru" name="Русский">
          <locale match="язык оригинала en" translate="перевод строки в match" />
      </language>
   <script>
</locales>`

в squirrel же написать функцию, которая вернет путь к этому файлу, и функция для возврата пути к текущему скрипту, а в самом squirrel написать обращение к нему для подачи строки типа такого:
`__("Original message")`
а функция __() в зависимости от AppLocale вернет нужный перевод.

По принципу что текст __() ровняется тому что есть в match в xml, можно ещё по ID обращения прикрутить. Но это уже внутри Squirrel, организация этого полная свобода, от вас только 2 функции :)

**Comment by zenden2k** [comment]
Один файл для всех скриптов? Мне не нравится. Скрипт должен сам себя переводить. 
Да и переводить там особо нечего. 

А чем вас этот вариант не устроил  ?
```javascript
function LanguageIsSupported(lang) {
    print("currentLocale = "+currentLocale);
    local def = "en";  //Язык по умолчанию
    local a = ["en", "ru"]; //Поддерживаемые скриптом языки
    if (lang in a) {
        return lang;
    } else {
        return def;
    }
};

function Translate(what) {
    print("tra called");
    local lang = LanguageIsSupported(currentLocale);
    print("lang = "+lang);
    local t = {
        "en" = {
            "Server ip or hostname [:port]" = "Server ip or hostname [:port]"
            "Remote folder" = "Remote folder"
            "Download path (ftp or http)" = "Download path (ftp or http)"
        }
        "ru" = {
            "Server ip or hostname [:port]" = "IP адрес/домен сервера [:порт]"
            "Remote folder" = "Удаленный каталог"
            "Download path (ftp or http)" = "ссылка загрузки"
        }
    }
    local loctbl = t.rawget(lang);
    if (what in loctbl)
        return loctbl.rawget(what);
    else
        return "NOT_TRASLATED";
};

В нужном месте вызывать:
function GetServerParamList()
{
    local a =
    {
        hostname = Translate("Server ip or hostname [:port]")
        folder = Translate("Remote folder")
        downloadPath = Translate("Download path (ftp or http)")
    }
    return a;
};
```

**Comment by arhangelsoft** [comment]
>Один файл для всех скриптов? Мне не нравится.

Ну куча xml Lang/Scripts/<scriptnme>.xml :)

> Скрипт должен сам себя переводить. 

Так и будет. 

>А чем вас этот вариант не устроил ?

не работает. Нельзя так таблицы строить:
  "Строка" = "Строка"

С XML будет куда проще.

**Comment by arhangelsoft** [comment]
Суть в том, что переводчику можно будет локализовать и скрипты.

**Comment by arhangelsoft** [comment]
и сообщения в лог.. и для MessageBox

**Comment by arhangelsoft** [comment]
Будут продвижения в этом плане?

**Comment by zenden2k** [comment]
Предлагаю сделать так
```javascript
function TR(text) {
  try {
    return Translate(text);
  }
  return text;
}
```
Потом я добавлю функцию Translate, которая будет переводить строки.

**Comment by arhangelsoft** [comment]
хм... перекинуть заботу перевода строки на ядро? Зачем?

**Comment by zenden2k** [comment]
Тоже верно, ведь у меня сервера обновляются отдельно от самой программы и файлов перевода.

**Comment by arhangelsoft** [comment]
пусть этим занимается скриптовая чсть, тем более сейчас все разобьётся на модули.

**Comment by zenden2k** [comment]
Пусть будет папка Languages в папке Scripts, а в ней просто текстовые файлы для каждого языка в формате 
исходная строка=перевод
XML формат неудобен

**Comment by arhangelsoft** [comment]
мм и как же их читать? Скриптов уйма :) Xml я потому и выбрал, что есть удобные средства его чтения.

**Comment by arhangelsoft** [comment]
а один/кучка xml в папке с ПО даст возможность переводчикам писать перевод.

**Comment by zenden2k** [comment]
Пусть будет JSON, в подпапке Languages, с таким же именем, как файл перевода программы, (надо будет добавить функцию GetAppLanguageFile()), 
и функция

```javascript
translation  <- null;
/**
@param key ключ разделенный точками
@param Исходная строка
**/
function TR(key, text) {
   try {
     if (!translation ) {
     translation = parseJson(GetFileContents(GetScriptsDirectory() +"Lang/"+GetAppLanguageFile()+".json"));
    }
    // Как нибудь достаем искомую строку из объекта translation используя key, при ошибке   возвращаем text
   } catch(ex) {
      return text;
   }
}
```

**Comment by arhangelsoft** [comment]
JSON не подходит. Будет гемморой с " и прочими знаками не приемлемыми в структуре JSON.

Я предлагаю так:
`function __t(defstr) {
	local ret = "";
	local xml = SimpleXml();
	local sScriptName = thisScriptNameNoExt();
	local sAppLocale = getAppLocale();
	if(xml.loadFromFile(getScriptsLanguageFile())) {
		local xroot = 	xml.getRoot("locales",false);
		local iScript = 0;
		local iScriptsCount = xroot.GetChildCount();
		for(iScript = 0;iScript < iScriptsCount; iScript++) { //enum script nodes
			local xnode = xroot.GetChildByIndex(iScript);
			if (node.attribute("name") == sScriptName) {
				local deflang = xnode.attribute("default");
				local iLangCount = xnode.GetChildCount();
				local iLang = 0;
				for(iLang = 0; iLang < iLangCount; iLang++) { //enum supported languages
					local xlang = xnode.GetChildByIndex(iLang);
					local sLocale = xlang.AttributeBool("locale");
					local bDef = xlang.AttributeBool("default");
					if (sLocale == sAppLocale) {
						local iPairsCount = xlang.GetChildCount();
						local iPair = 0;
						for(iPair = 0; iPair < iPairsCount; iPair++) { //enum pairs in lang
						    local xpair = xlang.GetChildByIndex(iPair);
							local sPattern = xlang.Attribute("pattern");
							local sMatch = xlang.Attribute("match");
							
							if (sPattern == defstr) {
								if(!bDef) {
									return sMatch;
								} else {
									return defstr;
								}
							}
						} /* //scripts/script/languages/lang/pairs enum */	
					} //found true language
				} /* //scripts/script/languages/lang enum */	
			} // found own script
		} /* //scripts/script enum */
	} // xml
}`

**Comment by zenden2k** [comment]
Какие знаки кроме кавычек неприемлимы в структуре JSON?

**Comment by zenden2k** [comment]
Да кстати ```local``` можно писать внутри ```for```
```javascript
for(local iScript = 0;iScript < iScriptsCount; iScript++) { //
``

**Comment by zenden2k** [comment]
Собственно вот
http://rawgit.com/zenden2k/image-uploader/master/Docs/api_i18n.html
сборка, в которой это всё можно попробовать
https://bintray.com/artifact/download/zenden/zenden-image-uploader/image-uploader-1.3.1a-build-4240-portable.7z
также добавил функции include,GetScriptsDirectory, GetAppLanguageFile.
