### ISSUE TITLE
Поменять в возвращаемой ссылке YaFotki.nut http на https

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#82]
Поменять в возвращаемой ссылке YaFotki.nut http на https.
ЯФотки вполне корректно работает по https.

У меня получилось что-то вроде такого

```
332c332,333
< directUrl = reg_replace(tempUrl,"_XL","_orig")+"."+GetFileExtension(FileName);

---
> directUrl = reg_replace(tempUrl,"_XL","_orig")+"."+reg_replace(GetFileExtension(FileName),"jpeg","jpg");
> directUrl = reg_replace(directUrl,"http:","https:");
```

Но я этот язык впервые вижу (jpeg/jpg заморочка это так, нужно было
ради одного сайта).
Заодно, думаю, можно попробовать заменить и все остальные http: на
https. Всякие oauth\* у них тоже умеют https.

**Comment by arhangelsoft** [comment]
>Заодно, думаю, можно попробовать заменить и все остальные http: на
> https. Всякие oauth* у них тоже умеют https.

Не факт. Но в целом, да.

**Comment by b-user** [comment]
Каков практический смысл замены http на https для публичных изображений ?
Особенно при большой вероятности публикации изображения на "http" форуме.

**Comment by zenden2k** [comment]
Не знаю. Можно сделать это опционально.
Но скрипт точно нужно поменять, там авторизация и загрузка идет по HTTP

**Comment by arhangelsoft** [comment]
>Каков практический смысл замены http на https для публичных изображений ?

Зависит от типа SSL сертификата у сайта. Может быть домен переведут на SSL а могут все домены включая поддомены.

**Comment by b-user** [comment]
Вопрос был о практическом смысле для пользователей браузеров читающих "http" форумы со вставками "https" изображений.

**Comment by zenden2k** [comment]
Не актуально
