### ISSUE TITLE
Создать класс и функции для регулярных выражений на основе PCRE

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#84]

**Comment by arhangelsoft** [comment]
Рекомендую назвать класс zRegExp. чтобы не было жесточайшего сходства с встроенным regexp.

**Comment by zenden2k** [comment]
Я его назвал CRegExp.
Ну собственно вот доки http://rawgit.com/zenden2k/image-uploader/master/Docs/api_regexp.html

попробовать можно в этой сборке
https://bintray.com/artifact/download/zenden/zenden-image-uploader/image-uploader-1.3.1a-build-4239-portable.7z

**Comment by zenden2k** [comment]
done
