### ISSUE TITLE
Исходники не собираются :)

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#85]
выловил последние сорцы баги такие:

ресурс Image uploader.rc:
нет файла res\icon_dropdown_png.png
фикс. путь:
IDB_ICONTOOLFILLEDRECTANGLE PNG                     "D:\\Develop\\imageuploader\\Source\\res\\ImageEditor\\icon_tool_filled_rectangle.png"

в source/3rdpart нет заголовочного
error C1083: Не удается открыть файл включение: 3rdpart/RoundRect.h: No such file or directory	f:\programming\mygithub\image-uploader\source\imageeditor\gui\toolbar.cpp

и ещё неведомая звурушка знает сколько ошибок :)

Поправьте пожалуйста

**Comment by zenden2k** [comment]
добавил недостающие файлы

**Comment by zenden2k** [comment]
пересобрал некоторые либы для vs 2013
https://bintray.com/artifact/download/zenden/zenden-image-uploader/Image_Uploader_Contrib_MSVC_2013_and_sources_v1.3.1.7z
теперь вроде компилируется и в vs 2013

**Comment by arhangelsoft** [comment]
Несколько вопросов:
1. Какую точно IDE используете для сборки проекта?
2. Что вы используете для удобной работы с Git?
3. Смотрите, у меня форк проекта, как мне корректно забирать ваши изменения себе на форк далее на локальный клон?

**Comment by zenden2k** [comment]
1. Я использую MS visual studio 2008 with service pack 1 professional
Но также попробовал собрать в ms vs 2013 professional, всё собралось
2. Я использую TortoiseGit (работает через контекстное меню проводника) но также у меня установлен Git for windows (http://git-scm.com/download/win) и иногда я кликаю правой кнопкой в папке и выбираю "Git bash here" чтобы выполнить команды
3. https://help.github.com/articles/syncing-a-fork/

**Comment by zenden2k** [comment]
Блин, по ошибке выложил архив без бинарных сборок библиотек. Перезалил архив.
