### ISSUE TITLE
Squirrel::Модульность кода и разделение на бинарный код и исходники

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#87]
Собственно нет надобнасти плодить один и тот же код в скриптах, 
достаточно создать папку utils и там расфасовать все как надо, что я и сделал.

Создал папку D:\utils\ там создал RegularExpressions.nut, в который выкинул вездесущие 
**regex_simple** и **regex_replace** из подопытного picuchka.nut в начале файла определил
`dofile("d:\\utils\\RegularExpressions.nut",true)`
из чего извлек профит ввиде полноценно работающего скрипта.

Но есть 1 проблема:
dofile требует абсолютного пути к файлу, значит надо описать ф-ию, которая вернет путь папки скриптов, где по-умолчанию будут лежать утилиты, или написать свою функцию, типа import("\\utils\\RegularExpressions.nut");
котора позаботится и о нахождении скрипта и о юниксовых путях и т.д. и т.п. в общем сама выполнит dofile как надо.

Далее, есть проблема:
измененный скрипт не всегда загружается UI заново, а после ошибок вообще никогда, приходится перезапускать IU. 
Предлагаю отделить исходники от компилированного кода.

В стандартной библе есть writeclosuretofile которая компилирует второй параметр и сохраняет его в файл(первый параметр), затем это можно выполнить через dofile, loadfile. 
В исходниках принцип тот же, сначала компиляция, потом исполнение в VM.

Может в дистрибьютиве лучше распространять компилированные скрипты?

**Comment by zenden2k** [comment]
Хорошо я добавлю функцию, возвращающую путь к папке со скриптами

**Comment by arhangelsoft** [comment]
а как быть юниксам в консольной версии? или оно не дружит со Squirrel?
Я имею ввиду такое dofile(getScriptsPath()+"\\utils\\asd.nut",true) приведет к такому:
**/usr/home/image uploader/scripts\utils\asd.nut**

**Comment by zenden2k** [comment]
использовать везде прямые слэши  / , они работают и на винде

**Comment by arhangelsoft** [comment]
добре

**Comment by zenden2k** [comment]
regex_replace надо переименовать в str_replace, потому что никакого regexp там нет и в помине

**Comment by zenden2k** [comment]
>Может в дистрибьютиве лучше распространять компилированные скрипты?
нет
>измененный скрипт не всегда загружается UI заново, а после ошибок вообще никогда, приходится перезапускать IU. 
Загружается заново только при ошибке компиляции.
