### ISSUE TITLE
ServerListTool: проверка сокращателей ссылок

### ISSUE THREAD

**Issue by zenden2k** [zenden2k/image-uploader#91]

**Comment by arhangelsoft** [comment]
Вариант, но есть идея прикрутить проверочный RegExp чтобы уж точно проверять укороченные линки. Хотя они и так будут меньше по длине строки и содержать домен ссылко-реза.

**Comment by zenden2k** [comment]
Просто запрашивать ссылку и сравнивать хедер Location: с исходной ссылкой
Предварительно выключив CURLOPT_FOLLOWLOCATION

**Comment by arhangelsoft** [comment]
Уверены, что это всегда на 100% работает?

**Comment by zenden2k** [comment]
Это я для ServerListTool говорю, а не для самой программы. В самой программе таким способом проверять не надо. Просто в скриптах или в servers.xml проверять regexp-ом

**Comment by arhangelsoft** [comment]
я тоже про эту утилиту, если уж проверять корректность серверов, то полностью :)
