### ISSUE TITLE
Редактор скринов, нельзя двигать рабочую область скрина после добавления объектов в неё.

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#93]
Доброго
Создам скрин, рабочую область в режиме редактора, можно двигать по экрану, все ещё выбирая место. С этим ясно.
Стоит в рабочую область докинуть стрелки, то двигать рабочей область по экрану уже не получится.

**Comment by zenden2k** [comment]
Её можно перемещать только при выбранном инструменте "Обрезка"
