### ISSUE TITLE
Параллельная загрузка на сервера

### ISSUE THREAD

**Issue by arhangelsoft** [zenden2k/image-uploader#94]
Сейчас как я понял, это в одном потоке, в порядке очереди. Что если сделать N очередей по N картинок из очереди на каждый поток?

**Comment by zenden2k** [comment]
В принципе была такая ветка 1.2.8 в которой была многопоточная загрузка
https://github.com/zenden2k/image-uploader/tree/1.2.8

вот даже сборка https://bintray.com/artifact/download/zenden/zenden-image-uploader/ImageUploader_1.2.8.7z

Но я столкнулся с рядом проблем, которые мне не удалось решить:
1. Текущая обертка для Squirrel (SqPlus) ни разу не многопоточная. Вернее она вообще как Singleton, одноинстансовая. Есть другая обертка (SqRat) и была даже попытка на нее перейти https://github.com/zenden2k/image-uploader/blob/1.2.8/Source/Core/Upload/ScriptUploadEngine_Sqrat.cpp, но мне не удалось реализовать некоторые функции, они вылетали, причину я найти не мог, а документация как всегда хромает.
2. Некоторые сервера блокируют многопоточную загрузку и выдают странные ошибки (?!?). Ну в принципе это обходится установкой MaxThreads для каждого сервера.
3. Была какая-то проблема с DNS-запросами, они иногда выдавали ошибки, я так и не смог тогда разобраться, почему.

**Comment by arhangelsoft** [comment]
хм, надо разобраться:
1. HTTP сервер может принимать файл кусками, так как и отдавать. Это можно делать многопоточно.
2. Многопоточно можно грузить пачку файлов на 1 хостинг в любом случае, каждому файлу по потоку и в путь.
3. Хостинг поддерживает одновременную загрузку более 1 файла за раз. Многопоточность также применима, если доступен п.1. Иначе это пачка картинок в 1 поток. Не катит.

Для первого и 3го пунктов, я бы предусмотрел такие атрибуты для server узла:
**range_upload** - сервер поддерживает прием файла по частям, значит можно 1 файл качать на сервер несколькими потоками. Хорошо для видео-файлов, и картинок более N мегабайт.
**multiple_files** - хостинг поддерживает загрузку пачки файлов 1 запросом.
**multiple_max** - сколько файлов хостинг скушает 1 запросом, если **multiple_files=yes**

> Текущая обертка для Squirrel (SqPlus) ни разу не многопоточная.

А сам Squirrel [поддерживает](http://squirrel-lang.org/doc/squirrel2.html#d0e1887) эту фичу.

может это как-то использовать? Все же скрипты полностью контролируют обмен данными с сервером.

**Comment by zenden2k** [comment]
>1. HTTP сервер может принимать файл кусками
По-подробнее

>2. Многопоточно можно грузить пачку файлов на 1 хостинг в любом случае,
Некоторые серверы выдают ошибку. Но это надо еще раз проверить

>3. Загрузка более 1 файла за раз ни разу не многопоточная

**Comment by arhangelsoft** [comment]
>По-подробнее

докинул ссылку.

>Некоторые серверы выдают ошибку. Но это надо еще раз проверить

для servers определить сколько потоков разрешить.


>Загрузка более 1 файла за раз ни разу не многопоточная. Если объединять запросы в один то экономия по времени мизерная.

Это возможность от сервера. Выбираешь сразу 10 файлов и оно пошло их обрабатывать. А 1 файл - 1 запрос - удобно, если этот сервер не ругется матом на параллельную загрузку.

**Comment by zenden2k** [comment]
> http://www.grid.net.ru/nginx/resumable_uploads.en.html

И какими серверами это поддерживается? Не помню из списка ни одного сервера, у которого аплод через ```Content-Disposition	attachment, filename="name of the file being uploaded"```

везде либо POST multipart/form-data либо PUT

**Comment by zenden2k** [comment]
В общем, надо перейти на [SqRat](http://scrat.sourceforge.net) а заодно наверно на Squirrel 3 (если они друг с другом совместимы), остальные проблемы решаемы. Можно сначала и не переходить на SqRat, просто сделать MaxThreads для скриптов = 1.

**Comment by arhangelsoft** [comment]
> И какими серверами это поддерживается?

надо смотреть. Не плохо было бы для видео. 

> но я не уверен насчет поддержки многопоточности при этом, по-моему, пока не загрузишь предыдущую часть, следующую нельзя отправлять. 

откуда такие мысли? Работает так же как и со скачиванием, выкачивает диапазон байт с клиента и пишет его в соотв. смещения в файле. Усе.
Скачивание так же работает.

> на Squirrel 3  

как раз хотел спросить, почему бы не переехать к ним. Однако не нахожу различий Scuirrel 2 и Squirrel 3.


тогда можно просто несколько картинок одновременно куда-то грузить.
Но в целом, поддержку хостингом загрузки сразу нескольких файлов, надо бы поддержать и здесь.

**Comment by zenden2k** [comment]
> откуда такие мысли?

Цитата отсюда https://www.dropbox.com/developers/core/docs#chunked-upload 

>If the offset you submit does not match the expected offset on the server, the server will ignore the request and respond with a 400 error that includes the current offset. To resume upload, seek to the correct offset (in bytes) within the file and then resume uploading from that point.

**Comment by arhangelsoft** [comment]
почему тогда скачивать таким образом можно? Можно же сразу с хваста кусок забрать и записать. Главное создать файл того же объема что и качаешь. Вероятно это в обе стороны работает.

**Comment by zenden2k** [comment]
Squirrel 3 поддерживает лямбда выражения

**Comment by zenden2k** [comment]
Всё не так плохо, как я предполагал, библиотека Sqrat сильно развилась с того времени, как я пробовал,
переход на Squirrel 3 и многопоточность должен пройти без проблем.

**Comment by arhangelsoft** [comment]
ура))

**Comment by zenden2k** [comment]
Черт, похоже придется отказаться от поддержки Windows 2000 ))))

**Comment by zenden2k** [comment]
Вот и первая сборка с поддержкой многопоточности 
http://zenden.ws/downloads/image-uploader-latest-beta-portable

**Comment by zenden2k** [comment]
В динамике неплохо смотрится)
![t](https://lh3.googleusercontent.com/-dqYhCQQew-I/VTO4CNTqL2I/AAAAAAAAEiU/b8q0pMSqc4w/s0/imageuploader_threads4.gif)

**Comment by zenden2k** [comment]
Модно считать закрытым в 1.3.2 alpha
