### ISSUE TITLE
Добавление сервиса dropmefiles.com

### ISSUE THREAD

**Issue by CB9TOIIIA** [zenden2k/image-uploader#96]
Возможно ли добавить dropmefiles.com для файлов и изображений? 
example: http://dropmefiles.com/aCY2t
до 50 ГБ на 7-14 дней

**Comment by zenden2k** [comment]
Недолго хранит, однако

**Comment by CB9TOIIIA** [comment]
Возможно, однако иногда надо скинуть файл объемный и 1-2 недели точно хватит на все это)

**Comment by arhangelsoft** [comment]
Они все не долго хранят.

**Comment by zenden2k** [comment]
Этот сайт борется с автоматическими загрузками и предлагает ввести капчу.

**Comment by pka-human** [comment]
> Этот сайт борется с автоматическими загрузками и предлагает ввести капчу.

Почему нельзя выводить изображение с капчей юзеру и просить ввести, если таковую просят? Сервис удобный, использую часто (вообще для загрузки/передачи чего-либо популярен).
